- apps/hyperdrive-trading/src/hyperdrive/BaseHyperdriveModel.ts
- apps/hyperdrive-trading/src/hyperdrive/steth/StethHyperdriveModel.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRedeemWithdrawalShares.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.ts
- packages/hyperdrive-js-core/package.json
- packages/hyperdrive-js-core/src/hyperdrive/ReadWriteHyperdrive.ts
- packages/hyperdrive-viem/package.json
- yarn.lock
Implement `onTransactionMined` into hyperdrive-core-js, plumb it through to open long as a first conversion.
> Upgrade to evm-client@0.2.4

- packages/hyperdrive-appconfig/src/generated/42069.appconfig.ts
Cloudchain is now on contracts v0.9.0
> Rebuild cloudchain appconfig

- apps/hyperdrive-trading/src/hyperdrive/BaseHyperdriveModel.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLpApy.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/YieldSourceApy.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
- apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts
Add ability on hyperdrive model to specify how the variable rate is fetched per chain.
> Add getYieldSourceRate to hyperdrive model

- apps/hyperdrive-trading/src/ui/landing/PositionCards/PositionCards.tsx
> Fix text casing on landing page

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/ClosedLongsTable/ClosedLongsTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/ClosedLpTable/ClosedLpTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/ClosedShortsTable/ClosedShortsTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortModalButton/OpenShortModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
- apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsTab/MarketDetailsTab.tsx
- apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx
> Move forms into modals, make tables full width

- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useMintToken.ts
#775 
https://github.com/delvtech/hyperdrive-frontend/assets/4524175/ee95cef0-e8ce-4f23-bb00-1f799b216021
> Display shares token balance, add ability to view and revoke allowances

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
- apps/hyperdrive-trading/src/ui/token/TokenChoices.tsx
> Don't show unavailable withdraw options

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortModalButton/OpenShortModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
- apps/hyperdrive-trading/tailwind.config.js
> Add emphasis on Open Position buttons, make Close positions more consistent

- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
> fixes tx table pagination

- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/PriceBadges.tsx
> adds skeleton for price badges in market header

- packages/hyperdrive-appconfig/src/generated/42069.appconfig.ts
Re-build the appconfig for cloudchain now that v0.10.1 contracts have been deployed
> Update appconfig for cloudchain

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useCloseLong.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.ts
Similar to the recent add/remove liquidity PR, this one adds a loading indicator to the open/close long position.
> Add loading indicator on openlong 

- apps/hyperdrive-trading/src/hyperdrive/BaseHyperdriveModel.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/useTransactionData.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
Related to #775 
|Desktop|Mobile|
|--|--|
|<img width="1315" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/ee196a32-5231-4085-b42e-72ec6f390b63">|<img width="472" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/8f10ec22-f71b-4ff0-a84b-bda624b82b66">|
> Fix bug causing remove liquidity to shares to be broken, add withdrawal shares to transaction table

- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
- apps/hyperdrive-trading/src/ui/token/TokenPicker.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.ts
#775 
Show the token icon in all the inputs now. Had to switch to the menu button dropdown component since select/option tags in HTML doesn't support images.
> Add token icons to inputs

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongModalButton/CloseLongModalButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/token/TokenPicker.tsx
Small polish to make our close buttons more consistent in our modals
> Add missing close buttons to modals

- apps/hyperdrive-trading/src/ui/base/components/Toaster/CustomToastMessage.tsx
- apps/hyperdrive-trading/src/ui/base/components/Toaster/ToastProvider.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
Make the toasts look more like our app:
> Cleanup toast design

- apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx
All toasts should now use the default "top-right" placement.
> Polish toasts for token approval tx

- apps/hyperdrive-trading/src/ui/base/components/LoadingButton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
This PR creates a custom loading button component that can be re-used but is currently used when a position type is opened and pending tx confirmation.
> custom loading button component

- apps/hyperdrive-trading/src/ui/base/formatting/formatDate.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
New date format for tables 28-Apr-2024
> updates format date

- apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx
- apps/hyperdrive-trading/src/ui/wallet/customTheme.tsx
> Adds switch chain icon

- apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useTradingVolume.ts
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
- apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
- apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx
> Add skeleton loaders on market stats 

- apps/hyperdrive-trading/src/ui/base/components/TableSkeleton.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/useTransactionData.ts
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/a9d40679-6896-4bcf-843f-2e11b8a52992
> adds skeleton on transactions table

- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
Related to #835 
First commit just reorganizes things in the file a bit (exports at the top, local functions below), the actual changes made after that are small
> Fix column sorting issues in Transaction Table

- packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
> Add `openVaultSharePrice` param to calcOpenShort calls

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
> Wire up max button to max long or wallet balance, whichever is smaller

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useCloseShort.ts
> Fix bug causing CloseShort button to always be enabled

- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useTradingVolume.ts
Fix bug causing trading volume stat to error out and report 0 volume. 
This was also causing a lot of extra skeleton loading renders since errors don't have a stale-while-revalidate policy.
Related #835
> Fix trading volume stat

- apps/hyperdrive-trading/src/ui/base/components/Pagination.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
> Add token icons to market header

- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
- apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModal.tsx
- apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModalButton.tsx
- apps/hyperdrive-trading/src/ui/token/TokenInput.tsx
This PR adds a revoke allowance modal where users can either revoke all spending privileges (set allowance to 0n) or set a custom spending cap. 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/85f98e77-7da4-4e77-8225-b22ce1e39faa
> Adds revoke allowance modal

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
Add a little extra allowance to make up for minor discrepancy between sdk's `calcOpenShort` method and the contract's `openShort` method.
This fixes the issue where you can't open a short after approving a one-time allowance for that trade.
Note: We have a ticket for making the sdk and contracts at parity with each other, at which point we can remove this 1% padding: https://github.com/delvtech/hyperdrive/issues/894
> Pad allowance for Open Short

- packages/hyperdrive-js-core/package.json
- packages/hyperdrive-viem/package.json
- yarn.lock
Upgrades evm-client to include https://github.com/delvtech/evm-client/pull/58
related to #837
> Upgrade evm-client

- apps/hyperdrive-trading/.env.sample
- apps/hyperdrive-trading/.gitignore
- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/scripts/build-app.sh
- apps/hyperdrive-trading/scripts/generate-walletconnect.sh
Implement Wallet Connect requirements, following this guide: https://docs.walletconnect.com/cloud/verify
The new .env variable has been added to the following vercel projects:
- `sepolia-production`
- `trading-competition-production`
Prior art: https://github.com/delvtech/council-kit/pull/416
> Add Wallet Connect

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
Adding these headings makes things easier to scan.
> Group sections in Open Long preview

- apps/hyperdrive-trading/.env.sample
- apps/hyperdrive-trading/src/routeTree.gen.ts
- apps/hyperdrive-trading/src/ui/app/App/App.tsx
- apps/hyperdrive-trading/src/ui/compliance/IneligibleAccountMessage.tsx
- apps/hyperdrive-trading/src/ui/compliance/hooks/useAddressScreen.ts
- apps/hyperdrive-trading/src/ui/routes/__root.tsx
- apps/hyperdrive-trading/src/ui/routes/index.tsx
- apps/hyperdrive-trading/src/ui/routes/market.$address.tsx
- apps/hyperdrive-trading/src/ui/routes/markets.tsx
- apps/hyperdrive-trading/src/ui/routes/void.tsx
- apps/hyperdrive-trading/src/version.output.ts
- turbo.json
> Implement TRM screening

- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
Updates the Your Balance section to include the sepolia faucet and show the mint button on all testnets.
> Show mint button on testnets, add sepolia faucet

- packages/hyperdrive-appconfig/src/scripts/sepolia.ts
Followup to #902 
Switching over to the newly deployed sepolia factory and registry contacts.
> Update sepolia factory and registry contracts

- apps/hyperdrive-trading/src/version.output.ts
- package.json
Ran into a few node_module cache errors debugging. This will make it quicker to reset node_modules.
> Add `reset-node-modules` script

- apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx
> Increase approval padding

- apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useMintToken.tsx
From testnet-channel: https://discord.com/channels/1092286014829113446/1227036483710488606/1227665969342713886
> Dismiss toasts after successful tx

- apps/hyperdrive-trading/src/ui/base/formatting/formatCompact.ts
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
> commify liquidity

- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/useTransactionData.ts
- packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
Closes #958 
All Transactions table now shows the latest transactions first
> Fix bug causing transaction table to show old trades first

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/token/TokenInput.tsx
- apps/hyperdrive-trading/src/ui/token/TokenPicker.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useSlippageSettings.ts
This is the same settings flow as it is for longs.
> Adds short slippage settings

- apps/hyperdrive-trading/src/network/wagmiClient.ts
- apps/hyperdrive-trading/src/ui/token/hooks/useMintToken.tsx
Minting in devnet should use the amount argument, while minting in sepolia should mint 1/2 the max mint amount.
Follow up to #921
> Fix minting

- apps/hyperdrive-trading/src/ui/analytics/getAnalyticsUrl.ts
- apps/hyperdrive-trading/src/ui/app/Footer/Footer.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
Closes #964 
| |
|--|
|Link to the specific market page in the Market header|
|<img width="1710" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/20712524-3ffd-4341-ad88-007d07c7de8a">|
|Link to the hyperdrive dashboard home page|
|<img width="1204" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/7e38dc83-2019-4523-bff9-8d6cd6b4ad40">|
> Add blockanalytica links

- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
> Add analytics link to navbar

- apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModalButton.tsx
Fixes this one:
|Before|After|
|---|---|
|<img width="520" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/5f447525-86c0-4ea8-bf65-e2cf1574676f">|<img width="545" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/defe5476-88f6-4c2c-b708-65c6bfbd16db">|
> Fix formatting for unlimited allowance

- apps/hyperdrive-trading/src/hyperdrive/model/steth/ReadWriteStethHyperdriveModel.ts
- apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.tsx
> Fix infinite spinner on Opening Long notification in steth markets

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/CurrentValueCell.tsx
This PR cleans up a bug on the current value component for open short positions. Now the logic is similar to the logic used on open longs pnl.
> cleanup profit loss label on shorts

- packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
In the LP APY formula: 
`r = ln(p_1 / p_0) / t`
the `t` parameter should be the time frame between p1 and p0, not the position duration. This brings the LP APY to the expected levels:
> fix time frame used for getLpApy calc

- apps/hyperdrive-trading/src/ui/app/App/App.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useIdleLiquidity.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/usePresentValue.ts
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/useMarketRowData.ts
- apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
> Add Total Value to market stats

- apps/hyperdrive-trading/src/base/formatTimeDifference.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
> Convert label from hours to days on large numbers

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
This PR adds the balances to the token picker on the close position preview modal.
> Fix close position balances on token picker

- .changeset/slimy-items-work.md
Update changeset for hyperdrive-js-core
> Update changeset for hyperdrive-js-core

- apps/hyperdrive-trading/src/hyperdrive/model/ReadHyperdriveModel.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
Fixes #997, but not for stETH markets. Those seem to require special treatment.
> fix calcs for when using shares on open long preview

- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/src/network/wagmiClient.ts
- apps/hyperdrive-trading/src/wallets/CreateWalletFn.ts
- apps/hyperdrive-trading/src/wallets/capsule.ts
- yarn.lock
> Upgrade capsule to v0.8.5

- apps/hyperdrive-trading/src/ui/landing/Hero/Hero.tsx
- apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx
- apps/hyperdrive-trading/src/ui/onboarding/FAQ/MobileFaq.tsx
The more green we use, the less power it has as the "primary" color.
> Quiet down colors in FAQ

- apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
> Update color on Term Complete label

- apps/hyperdrive-trading/src/base/formatRate.ts
- apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
Bunch of small polish commits i had racked up in another branch
> Minor UI polish

- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
Calc has been updated and we've settled on `Short APY` as the label. This PR makes that change and pulls off the feature flag.
> Remove feature flag from Implied Yield stat

- apps/hyperdrive-trading/src/hyperdrive/getReadHyperdrive.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useReadHyperdrive.ts
- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceCard/YieldSourceCard.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTable.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/useRowData.ts
- apps/hyperdrive-trading/src/ui/routes/__root.tsx
- packages/hyperdrive-appconfig/src/appconfig/helpers/findYieldSourceHyperdrives.ts
- packages/hyperdrive-appconfig/src/index.ts
- packages/hyperdrive-appconfig/src/protocols/protocols.ts
Wires up the cards to real data and makes rows clickable
This is still behind feature flag, as mobile has not been addressed yet.
> Wire up the card layout

- apps/hyperdrive-trading/src/ui/app/Navbar/FeatureFlagPicker.tsx
- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
- apps/hyperdrive-trading/src/ui/landing/PositionCards/PositionCards.tsx
- apps/hyperdrive-trading/src/ui/markets/Markets.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx
Make Tile layout the default now. While here i made a few other small cleanups..
> Remove feature flag on tile layout

- apps/hyperdrive-trading/src/ui/app/Footer/Footer.tsx
Adding a footer link to the v1 pools.
> Add link to v1 pools

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useImpliedRate.ts
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketBreadcrumbs.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/useRowData.ts
> Show '-' when no short hpr can be calculated

- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
First of a few changes coming in based on discussions around APR and ROI.
> Relabel HPR to ROI instead

- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
ROI is not annualized like APR is
> Fix Short ROI tooltip text

- apps/hyperdrive-trading/.env.sample
- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/src/ui/main.tsx
- turbo.json
- yarn.lock
This adds rollbar error tracking to the UI. By default any uncaught frontend errors will be sent to rollbar so we can inspect them.
Rollbar env vars have been added to the staging and production Vercel projects.
> Add rollbar

- apps/hyperdrive-trading/src/base/queryStatus.ts
- apps/hyperdrive-trading/src/ui/app/Navbar/FeatureFlagPicker.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useFixedRate.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useShortRate.ts
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/FixedRateStat.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/ShortRateStat.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/ShortRateCell.tsx
- packages/hyperdrive-viem/package.json
Closes #1108 
- Adds the APR and ROI toggle for the Short rate.
- Removes the feature flag
https://github.com/delvtech/hyperdrive-frontend/assets/4524175/c4f3e5d6-4662-4716-b532-75d20168cb69
> Add Short APR and Short ROI toggle

- apps/hyperdrive-trading/src/base/calculateTimeLeft.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
Shows the hours and minutes left when a position has less than 1 day left:
Closes #1127
> Show the time left in hours & minutes if less than a day is left

- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
> Adds adjust slippage error to LP preview

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useTotalOpenLongsValue.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useTotalClosedShortsValue.ts
- apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
- apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx
This PR adds a warning icon if the total value of all positions can't be calculated.
Closes #1186
> Adds warning if total value can't be calculated

- apps/hyperdrive-trading/src/ui/compliance/TermsOfUseAndPrivacyPolicyModal.tsx
> give tos modal some breathing room

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
> Fix flag for Bridge UI

- apps/hyperdrive-trading/.env.sample
- apps/hyperdrive-trading/src/ui/appconfig/useAppConfig.ts
- packages/hyperdrive-appconfig/src/generated/1.appconfig.ts
- packages/hyperdrive-appconfig/src/index.ts
- packages/hyperdrive-appconfig/src/scripts/mainnet.ts
Co-authored-by: Danny Delott <DannyDelott@users.noreply.github.com>
> Build mock app config for mainnet

- .vscode/settings.json
- apps/hyperdrive-trading/index.html
- apps/hyperdrive-trading/src/ui/app/Head/CommonHeadTags.tsx
- apps/hyperdrive-trading/src/wallets/capsule.ts
> Remove hardcoded URLs

- apps/hyperdrive-trading/src/ui/app/Footer/Footer.tsx
> Final footer

- apps/hyperdrive-trading/src/ui/compliance/IneligibleAccountMessage.tsx
Changes "Ineligible Account" to "Ineligible Wallet Address".
> Tweak compliance messaging

- apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx
Adding more prominent link styling to better emphasize the active question in the FAQ
> Tweak FAQ style

- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/withdrawalShares/RedeemWithdrawalSharesForm/RedeemWithdrawalSharesForm.tsx
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/f1e5e48d-be7c-4e49-be5a-b5ff2cf6f255
> Adds slippage adjustments to withdraw LP and redeemWithdrawalshares form

- apps/hyperdrive-trading/.eslintrc
- apps/hyperdrive-trading/src/ui/base/components/Modal/Modal.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useAggregationSolution.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useChains.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useChainsByChainId.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useHealth.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useToken.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useTokenBalances.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useTokens.tsx
Adding a rule to enforce that exported functions are written as function declarations.
> Add func-style rule to eslint

- apps/hyperdrive-trading/src/ui/bridge/TokenBalances/TokenBalances.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useAggregationSolution.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useToken.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useTokenBalances.tsx
Small tweaks to some gopher hooks
> Update Gopher hooks

- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetPicker.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsActionButtons.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsForm.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgePreview.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsModal/BridgeAssetsModal.tsx
- apps/hyperdrive-trading/src/ui/bridge/TokenBalances/TokenBalances.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
Adds most of the modal UI for bridging assets.
> Add bridge modal UI

- apps/hyperdrive-trading/src/bridge/stubs/assets.ts
- apps/hyperdrive-trading/src/bridge/stubs/balances.ts
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetPicker.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsForm.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgePreview.tsx
- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsModal/BridgeAssetsModal.tsx
- apps/hyperdrive-trading/src/ui/bridge/Chains/Chains.tsx
- apps/hyperdrive-trading/src/ui/bridge/TokenBalances/TokenBalances.tsx
- apps/hyperdrive-trading/src/ui/bridge/Tokens/Tokens.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeChains.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeChainsByChainId.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeHealth.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeToken.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeTokenBalances.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useBridgeTokens.tsx
- apps/hyperdrive-trading/src/ui/bridge/hooks/useChainName.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
- add 'Bridge' to bridge hooks for clarity
- conditionally show bridge link
> Only show bridge ui link if user has assets in L2s

- apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsActionButtons.tsx
- add base/b3 sepolia chains
- connect to appropriate chain before approve
- wire up approve button
> Wire up bridge Approval Button

- apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
- package.json
> Add default active for longs tab, remove unused npm script

- .github/workflows/release.yml
- package.json
This reverts commit af14cb9568e68826bdaee2b5788dd7a13deadfb2.
> Fix release

- apps/hyperdrive-trading/src/routeTree.gen.ts
- apps/hyperdrive-trading/src/ui/app/EmptyContainer.tsx
- apps/hyperdrive-trading/src/ui/app/Page.tsx
- apps/hyperdrive-trading/src/ui/compliance/IneligibleAccountMessage.tsx
- apps/hyperdrive-trading/src/ui/compliance/VpnDetectedMessage.tsx
- apps/hyperdrive-trading/src/ui/compliance/hooks/useAddressScreen.ts
- apps/hyperdrive-trading/src/ui/compliance/hooks/useVpnScreen.ts
- apps/hyperdrive-trading/src/ui/routes/__root.tsx
- apps/hyperdrive-trading/src/ui/routes/error.tsx
- apps/hyperdrive-trading/src/ui/routes/ineligible.tsx
- apps/hyperdrive-trading/src/ui/routes/restricted_countries.tsx
- apps/hyperdrive-trading/src/ui/routes/void.tsx
- apps/hyperdrive-trading/src/ui/routes/vpn.tsx
Refactors the compliance screening to only happen in the `Page` component and simplified the hooks.
> Refactor compliance screening

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/FixedRateCell.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
> Remove extra percents

- packages/hyperdrive-js-core/src/hyperdrive/base/v1.0.14/ReadHyperdrive_v1_0_14.ts
> Fix conversion causing fixed rate quotes to be off on v1.0.14 hyperdrives

- packages/hyperdrive-js-core/src/shorts/calculateShortAccruedYield.ts
This should be removed once negative values can be passed to fixed-point-wasm.
> adjust short accrued yield calc

- apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/getRemainingTimeLabel.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongModalButton/CloseLongModalButton.tsx
- apps/hyperdrive-trading/src/ui/token/TokenInputTwo.tsx
This PR updates the design for CloseLongForm according to the figma. 
https://github.com/user-attachments/assets/7a7afc8a-060e-4785-87fe-c3e2b321301d
> Update close long design

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
https://github.com/user-attachments/assets/a98ef057-af13-4ff0-96c9-5db4cc9b9d8c
> Fix error state on close long form

- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useTokenFiatPrices.ts
Wires up the TVL stat on the new pool rows.
> Wire up TVL to fiat price

- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/scripts/build-app.sh
- apps/hyperdrive-trading/src/version.output.ts
- apps/hyperdrive-trading/vite.config.build.ts
- apps/hyperdrive-trading/vite.config.ts
This will let us use the feature flags on app-staging. Will update the vercel command for the staging project once this lands.
> Add development mode to app-staging

- apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
- apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
- apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
|Half-size browser|Mobile|
|---|---|
|<img width="965" alt="image" src="https://github.com/user-attachments/assets/6e991b6c-da45-413b-ae75-0f3709c476be">|<img width="495" alt="image" src="https://github.com/user-attachments/assets/9ff2e779-7683-49bd-8719-06cb75bcadf7">|
> Add mobile support on All Pools Page

- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
- apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
- yarn.lock
Show a lightening bolt next to the variable apy and lp apy on pools that have rewards.
Note: `yarn.lock` updated here as packages were removed in #1382, but yarn wasn't rerun in that PR.
> Add rewards to new all pools page

- apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
Makes the whole pool row clickable
> Make row clickable on Pool row

- packages/hyperdrive-appconfig/src/generated/1.appconfig.ts
- packages/hyperdrive-appconfig/src/generated/11155111.appconfig.ts
- packages/hyperdrive-appconfig/src/generated/42069.appconfig.ts
- packages/hyperdrive-appconfig/src/generated/all.appconfig.ts
- packages/hyperdrive-appconfig/src/yieldSources.ts
Update according to their rate period (asked in their Discord server)
> update EtherFi historicalRatePeriod to 30 days

- apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
Removes the flag, adds a link to the navbar, though it looks like we don't have a navbar at the top anymore...  not sure how y'all wanna route to the page.
> remove bridge flag

- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
> Show link to All Pools and Bridge pages in navbar

- apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLpApy.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/StatusCell.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewOpenLong.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/ShortRateAndSizeCell.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/usePreviewOpenShort.ts
- apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
- apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
- apps/hyperdrive-trading/src/ui/token/ApproveTokenChoices.tsx
- apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModalButton.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useMintToken.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useTokenAllowance.ts
- apps/hyperdrive-trading/src/ui/token/hooks/useTokenBalance.ts
This PR adds chainId to the following wagmi hooks:
- useContractRead
- useBlockNumber
- useBlock
> Adds chainId to wagmi hooks

- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/src/blockexplorer/blockExplorers.ts
- apps/hyperdrive-trading/src/blockexplorer/makeAddressUrl.ts
- apps/hyperdrive-trading/src/blockexplorer/makeTransactionUrl.ts
- apps/hyperdrive-trading/src/ui/appconfig/useAppConfig.ts
- apps/hyperdrive-trading/src/ui/chainlog/AddressCell.tsx
- apps/hyperdrive-trading/src/ui/chainlog/ChainCell.tsx
- apps/hyperdrive-trading/src/ui/chainlog/Chainlog.tsx
- apps/hyperdrive-trading/src/ui/chainlog/FactoriesTable.tsx
- apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx
- apps/sdk-sandbox/scripts/example.ts
- packages/hyperdrive-js-core/src/factory/ReadFactory.ts
- packages/hyperdrive-js-core/src/registry/ReadRegistry.ts
- packages/hyperdrive-js-core/src/registry/ReadWriteRegistry.ts
- yarn.lock
> Make chainlog multichain

- packages/hyperdrive-viem/package.json
- yarn.lock
Co-authored-by: Danny Delott <DannyDelott@users.noreply.github.com>
> Bump evm-client-viem

- apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
Cleans up the devmode warning about Button within button on the pools page.
> Fix invalidDomNesting error

- apps/hyperdrive-trading/index.html
- apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
- apps/hyperdrive-trading/src/ui/markets/AssetStack.tsx
- apps/hyperdrive-trading/src/ui/markets/Market.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
- apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails/PoolDetails.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails/PoolHeader.tsx
- apps/hyperdrive-trading/tailwind.config.js
Implemented a `pool-details-v2` feature flag to support the development of the new Pool Details page and began work on related components. Additionally, I replaced the inline SVG in `index.html` with a `background-image` CSS property applied to the root element.
> Add feature flag for pool details v2

- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm2.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails/PoolDetails.tsx
- apps/hyperdrive-trading/src/ui/markets/PositionPicker/PositionPicker.tsx
- apps/hyperdrive-trading/src/ui/token/TokenInputTwo.tsx
Connecting the Short and Supply buttons
[182d-Maker-DSR---Hyperdrive.webm](https://github.com/user-attachments/assets/f6c0d8d8-bb4c-4153-a768-3c68fdabc30f)
> Wire up Short and Supply forms

- apps/hyperdrive-trading/src/ui/rewards/useRewards.ts
> Fix LP rewards calculation

- apps/hyperdrive-trading/src/ui/markets/PositionPicker/PositionPicker.tsx
- apps/hyperdrive-trading/src/ui/token/TokenPickerTwo.tsx
Fixes the token input layout by keeping the token picker size consistent, whether there’s one token or more.
> Polish new Pool Details form

- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
- apps/hyperdrive-trading/src/ui/base/components/AccordionSection/AccordionSection.tsx
- apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails/PoolDetails.tsx
- apps/hyperdrive-trading/src/ui/onboarding/FAQ/faqData2.tsx
- apps/hyperdrive-trading/tailwind.config.js
- yarn.lock
Putting the bond amount in the transaction details instead of in the primary stat:
> Polish navigation, show maturity date below rate in Open Long form

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
Fixes bug found during today's Jam session.
> Fix bug in close long form causing estimates not to render in input box

- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm2.tsx
- apps/hyperdrive-trading/src/ui/token/hooks/useActiveToken.ts
Handful of polish items to the Pool Details components
> Polish tooltips, split up components, fix alignments

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm2.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm2.tsx
This makes sure the buttons are disabled when the pool is paused.
> Disable buttons on open forms when market is paused

- apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
- apps/hyperdrive-trading/src/ui/markets/Market.tsx
- apps/hyperdrive-trading/src/ui/token/SlippageSettingsTwo.tsx
> Remove feature flags for Pool Details v2 and Portolio pages

- apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx
The chainlog was breaking after a pool was removed from the registry until the config was rebuilt. This refactors the pools table to get the list directly from the registries.
> Get chainlog pool list from registry

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
Moving the variable rate into the `Earn Yield On` input.
> Show vault rate in Earn Yield On

- apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolsList.tsx
> Add asset filter to pools list

- apps/hyperdrive-trading/src/ui/markets/PoolRow.tsx
- apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
- apps/hyperdrive-trading/src/ui/rewards/useMorphoRate.ts
- apps/hyperdrive-trading/src/ui/rewards/useRewards.ts
This PR adds a hook for fetching dynamic Morpho rewards data from this api:
https://rewards.morpho.org/
https://github.com/user-attachments/assets/f1f81c15-c86e-4815-b31a-9e020107948d
> Adds Morpho Rewards endpoint

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/app/App/App.tsx
- apps/hyperdrive-trading/src/ui/app/Page.tsx
- apps/hyperdrive-trading/src/ui/main.tsx
- apps/hyperdrive-trading/src/ui/routes/__root.tsx
- apps/hyperdrive-trading/src/ui/routes/restricted_countries.tsx
- Refactors the `Plausible` component to only handle adding the script and prepping the function.
- Simplifies `"pageview"` event logic.
- Adds tracking for the `walletConnect` and `walletDisconnect` events.
closes: #1531
> Add wallet connect/disconnect plausable events

- apps/hyperdrive-trading/src/ui/markets/PoolRow.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx
Move data loading back into the pool rows so that the pools list loads faster. This requires removing the ability to sort temporarily.
[Hyperdrive---DeFi-Yield-your-way (6).webm](https://github.com/user-attachments/assets/fb5b6c7d-db13-4eba-91d7-a4194d3859f6)
> Fix slow loading time on pool rows, remove sorting

- apps/hyperdrive-trading/src/ui/app/Footer/Footer.tsx
> adds home link to footer

- .changeset/dirty-coins-itch.md
- apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
- apps/hyperdrive-trading/src/ui/rewards/useRewards.ts
- packages/hyperdrive-appconfig/src/index.ts
> adds etherfi rewards tooltip

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewOpenLong.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/usePreviewOpenShort.ts
> watch to false

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx
> Add `"filterChange"` plausible event

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/compliance/TermsOfUseAndPrivacyPolicyModal.tsx
> Add `"termsAndPrivacyView"` & `"termsAndPrivacyAccept"` plausible events

- apps/hyperdrive-trading/src/ui/compliance/TermsOfUseAndPrivacyPolicyModal.tsx
- apps/hyperdrive-trading/src/ui/compliance/hooks/useTermsOfUseAndPrivacyPolicyAccepted.ts
The event is firing on every render, even when not shown.
> Fix `"termsAndPrivacyView"` event

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
> Add `"transactionDetailsOpen"` plausible event

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/ManageLongsButton.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/YieldMultiplierCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PositionPicker.tsx
- apps/hyperdrive-trading/src/ui/routes/market.$chainId.$address.tsx
> Add `"positionTypeChange"` event

- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useCloseLong.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useAddLiquidity.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRedeemWithdrawalShares.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRemoveLiquidity.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useCloseShort.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.tsx
closes: #1534
Related to:
- #1535
- #1536
- #1538
- #1540
> Add `"transactionSubmit"` & `"transactionSuccess"` plausible events

- .vscode/settings.json
My Biome plugin keeps trying to format with my personal biome config.
> Add default formatter to vscode settings

- apps/hyperdrive-trading/src/ui/portfolio/NoWalletConnected.tsx
- apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
- apps/hyperdrive-trading/src/ui/portfolio/longs/LongsContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/rewards/useRewardsData.ts
- apps/hyperdrive-trading/src/ui/portfolio/shorts/ShortsContainer.tsx
Adds the `RewardsContainer` with some basic scaffolding and DRY up more duplicated code in the portfolio.
> Scaffold Rewards tab

- apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx
Pinning for two weeks, see #1663
> Pin sGYD pool to top of list

- apps/hyperdrive-trading/src/base/formatRate.test.ts
- apps/hyperdrive-trading/src/ui/analytics/ExternalLink.tsx
- apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
- apps/hyperdrive-trading/src/ui/app/App/App.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useCloseLong.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useAddLiquidity.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRedeemWithdrawalShares.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRemoveLiquidity.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useCloseShort.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolDetails.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/YieldMultiplierCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx
- apps/hyperdrive-trading/src/ui/markets/PositionPicker.tsx
- apps/hyperdrive-trading/src/ui/routes/__root.tsx
> Add `connectedWallet` to events

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyStat.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
- apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
We now show the rewards ⚡️ tooltip in Open Short. While here I also unified the rewards tooltip into its own component:
> Add rewards to Open Short form

- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyStat.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
- apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
Adding rewards tooltip to the Add Liquidity form:
> Add Rewards to Add Liquidity form

- apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useUnpausedPools.ts
- apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
- apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts
Hotfix to disable sorting while we troubleshoot an infinite loop
> Temporarily disable sorting

- apps/hyperdrive-trading/package.json
- apps/hyperdrive-trading/src/ui/base/components/CustomBanner.tsx
- apps/hyperdrive-trading/src/ui/markets/PointsMarkets/PointsMarkets.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
- apps/hyperdrive-trading/src/ui/rewards/MilesBanner.tsx
- apps/hyperdrive-trading/tailwind.config.js
- yarn.lock
Banner text is now centered, making it easier to scan the page.
> Center text on miles banner

- apps/hyperdrive-trading/src/ui/markets/PointsMarkets/PointsMarkets.tsx
- apps/hyperdrive-trading/tailwind.config.js
Minor polish to the Points Markets page
> Remove extra `Rewards Multiplier` row, soften glow

- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
- apps/hyperdrive-trading/src/ui/portfolio/longs/LongsContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/shorts/ShortsContainer.tsx
Some tiny polish items noticed when using the app..
> Copy update and add link styling

- apps/hyperdrive-trading/src/ui/base/formatting/formatCompact.ts
- apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
- apps/hyperdrive-trading/src/ui/landing/Landing.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolStat.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyCta.tsx
- apps/hyperdrive-trading/src/ui/token/TokenInput.tsx
Handful of #1629 stuff to start the day
> Fix TVL label, improve copy, fix horizontal scrolling

- apps/hyperdrive-trading/src/ui/markets/PointsMarkets/PointsMarkets.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
> Add message to spinner on all pools and points markets page

- apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
Fixing the double tooltip. h/t @cashd for spotting this.
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/802aadc2-82c8-40b4-a015-3d31fefa71c9)|<img width="522" alt="image" src="https://github.com/user-attachments/assets/39bd73b4-befa-4760-8bd1-0520911ba95e" />
|
> Fix double tooltip

- apps/hyperdrive-trading/package.json
- yarn.lock
Upgrading to the latest `viem`, `wagmi`, and `rainbowkit` packages.
> Upgrade wagmi, viem, and rainbowkit

- .changeset/two-squids-help.md
Been a while since we did an appconfig release, and we'll need to depend on it for the rewards work @sentilesdal  is doing.
> Add changeset

- apps/hyperdrive-trading/scripts/generate-rewards-swagger.sh
- apps/hyperdrive-trading/src/rewards/generated/RewardsClient.ts
- apps/hyperdrive-trading/src/rewards/generated/rewards-swagger.json
- apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsTableDesktop.tsx
Updates to the latest swagger, which includes a `pendingAmount` field.
> Add `Pending earnings` and `Claimable` columns to rewards

- apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/rewards/merklDistributorAbi.ts
- yarn.lock
- Adds the merklDistributorAbi for claiming Hyperdrive Miles.
- Handles claim button edge case:
-  when a merkleProof hasn't been generated yet, you can't claim, so disable the button.
> Add merklDistributorAbi, handle edge case in Claim button

- apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
Closes #1767
https://github.com/user-attachments/assets/3e8964ea-7c53-4e30-a01b-776a9135b781
> mobile hamburger menu added

- apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
- apps/hyperdrive-trading/src/ui/base/components/ResponsiveText.tsx
- apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
This PR adds responsive text sizing to the "You Receive" primary stat. This is important for Morpho pools where LP values can be very large.
https://github.com/user-attachments/assets/5d7ebc92-7834-4f23-a44d-28da6ac6fecf
> Responsive Text (You Receive)

- apps/hyperdrive-trading/package.json
- yarn.lock
Followup to #1801 
Upgrading the radix tooltip package, which has had 6 bugfix versions since we last updated. Hoping there's something in there to fix the intermittent crash
> Update radix tooltip package

- apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
Fixes Fixed APR calc for Longs when paying with shares (#1804)
> calc long fixed apr based on amount of base paid

- apps/hyperdrive-trading/src/rewards/merklUserRewards.ts
- apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimReward.tsx
Quick fixes to the typecheck failures from #1807
> Fix broken type-checks 

- apps/hyperdrive-trading/src/rewards/milesLeaderboard.ts
This PR changes the leaderboard numbers to show all-time Miles earned instead of unclaimed Miles.
> Switch to all-time rewards in Leaderboard

- apps/hyperdrive-trading/src/ui/base/components/MultiSelect.tsx
- apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
- apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts
- apps/hyperdrive-trading/src/ui/routes/index.tsx
> Add hide low TVL filter

- apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesTable/LpAndWithdrawalSharesTable.tsx
- apps/hyperdrive-trading/src/ui/portfolio/rewards/PoolHasRewardsBanner.tsx
- apps/hyperdrive-trading/src/ui/portfolio/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
- apps/hyperdrive-trading/src/ui/rewards/MilesBanner.tsx
Display a message over positions in the portfolio which are also accruing rewards of some kind.
> Add reward banner to portfolio Short and LP tabs

- apps/hyperdrive-trading/src/ui/portfolio/longs/LongsContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/shorts/ShortsContainer.tsx
- apps/hyperdrive-trading/src/ui/portfolio/shorts/usePortfolioShortsData.ts
- packages/hyperdrive-js/src/hyperdrive/ReadHyperdrive.ts
Render the NonIdealState if the user doesn't have any shorts, or all their shorts have a 0 balance
> Fix empty state when a user has no open shorts

- apps/hyperdrive-trading/src/ui/compliance/privacyPolicy.ts
- apps/hyperdrive-trading/src/ui/compliance/termsOfUse.ts
moved them from AWS to this repo
> update the link to privacy policy and tos
