delvtech/hyperdrive-frontend

apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx

This PR adds a non-ideal state if there are no transactions for filtered position types. This gives clarity to users (rather than an empty table) and it fixes the dropdown overflow issue on #775

Adds nonideal state if no filtered positions

---

apps/hyperdrive-trading/src/ui/base/components/Tabs/Tabs.tsx
apps/hyperdrive-trading/src/ui/globals.css
apps/hyperdrive-trading/src/ui/markets/TransactionsAndFaqTabs/TransactionsAndFaqTabs.tsx

#775 
Tab section border now matches the border for the market stats, making the sections pop a bit more
|Before|After|
|---|---|
|<img width="1346" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/8290b61b-291e-4832-95eb-9266dabf1de2">|<img width="1353" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/4ffa041e-ba1b-4443-886d-eccf1eae906c">|

Improve tab section border visibility

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortModalButton/OpenShortModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
apps/hyperdrive-trading/tailwind.config.js

Reverting some polish from #781, where I made these more round by default. Since this variable also governs input radiuses and input + button groups, which we don't want to change.

Undo rounding tailwind change

---

apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx

This PR fixes the market stats tooltip being cutoff on smaller screens. It introduces a tooltipPosition prop to the stat component. Ideally when there is more bandwidth we can implement a better tooltip library that allows for different placement so the other stats aren't covered (see video). But this fixes the cutoff issue. Fixes issue on #775 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/3bcd769c-e651-45e7-bc16-ea1eb255d046

Fixes market stats tooltips on smaller screens

---

apps/hyperdrive-trading/src/ui/token/TokenInput.tsx

Users shouldn't be allowed to type in negative numbers or exponential shorthand, eg: "1e10"

Disallow typing in negative sign or 'e' into inputs

---

apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTable.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx

This PR fixes the all markets table on mid-sized screens. Based on feedback, users had a hard time reading the label/values on the mobile table since they were so far apart.
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/b7b530cf-cca9-489d-a092-0f75d29cf9f7

Fixes all markets table on mid-sized screens

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useAddLiquidity.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRemoveLiquidity.ts

This PR cleans up the add/remove liquidity toast flow. The modal is closed after the user approves the transaction and a toast is shown indicating the pending transaction. 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/183e9ee2-84d3-4450-812a-aea4ae66322d

Adds pending liquidity toasts

---

apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTable.tsx
apps/hyperdrive-trading/src/ui/routes/__root.tsx

Wide screens rejoice! The logo and wallet components now live in the same column as the content.

Move app header into same column as content

---

apps/hyperdrive-trading/src/ui/base/formatting/formatDate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/ClosedLongsTable/ClosedLongsTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/ClosedLpTable/ClosedLpTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/ClosedShortsTable/ClosedShortsTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/version.output.ts

Adding a `formatDate` method so we can render dates consistently everywhere

Unify date formatting

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/LpApyCell.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

The calc for lp apy had a bug:
Before:
`r = ln(p_1 / p_0 / t)`
After:
`r = ln(p_1 / p_0) / t`
This brings the lp apy back to normal numbers:

Fix bug in LP APY calculation

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/ClosedLongsTable/ClosedLongsTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/ClosedLpTable/ClosedLpTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/ClosedShortsTable/ClosedShortsTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx
apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsTab/MarketDetailsTab.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx

The LP APY is actually showing the 7d stats, so the label was updated to reflect that. I also fixed the awkward padding on our tables so now they extend the full width of the card.
|Before|After|
|--|--|
|<img width="1299" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/c1bbf177-94e4-4cff-bd42-be916541c556">|<img width="1364" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/86171065-e44a-4207-a30a-d00b6685a7a8">|

Change 12h -> 7d in LP APY, full width position tables

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useOpenLpPosition.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.test.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

#775 
- The current value of an LP position now comes from the SDK and is shown in the Open LP Card.
Display the positive slippage:

Fix LP Shares current value

---

apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx

Showing the full chain name instead of an icon, since not all chains will be configured with one.
|Before|After|
|---|---|
|<img width="1263" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/0e3c0631-9640-4676-b0c9-ef707d405aec">|<img width="1271" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/3b6eee27-6964-4a14-804e-59ceaa5dd165">|

Display full name of chain

---

apps/hyperdrive-trading/src/ui/base/components/LoadingState.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx

Events might load slowly, but if users see a spinner for too long, they might think something's wrong. Adding this info to the spinner tells them, "We're working on it, so hang tight!"

Add descriptions to loading state component

---

apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx

Forgot the `id` field on this one which makes toasts able to update in-place instead of rendering two toasts.
Related to #835

Fix token approval toast

---

apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx
apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx
apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx

Two things are throwing off the mobile layout. First, there isn't enough room for the feature flag picker on mobile. Since we don't currently have feature flags and it will still be available on desktop, I've removed it on mobile. Second, the tooltips in market stats, while not visible, are still causing a layout issue. I've updated the tooltip positions on mobile so there's no longer a horizontal scroll.
Before:
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/73865d35-4a74-4928-8acd-9b0b9a035e94
After:
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/2177758f-84e0-4774-a02b-0173ab0e0b1d

Fix mobile alignment

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityPreview/AddLiquidityPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx

https://github.com/delvtech/hyperdrive-frontend/assets/4524175/916e8bf3-021e-463d-a35d-8d03bc6df9c6
Closes #875

Use LP Shares in LP tab

---

.changeset/new-lizards-tie.md
apps/hyperdrive-trading/package.json
packages/eslint-config/package.json
packages/hyperdrive-appconfig/package.json
packages/hyperdrive-artifacts/package.json
packages/hyperdrive-js-core/package.json
packages/hyperdrive-viem/package.json
packages/prettier-config/package.json
packages/spark/package.json

Updates the licenses to match the repo and adds the missing `publishConfig` field to the `package.json` for `@delvtech/hyperdrive-artifacts` to fix the release workflow.

Update package.jsons, fix artifacts release

---

apps/hyperdrive-trading/src/network/wagmiClient.ts
apps/hyperdrive-trading/src/wallets/capsule.ts

The app was crashing when I had Sepoila configured, but didn't include the capsule env vars.

Ignore capsule if not configured

---

apps/hyperdrive-trading/src/ui/markets/MarketStats/MarketStats.tsx

There might be a better way to handle this but we use the same snippet to solve this negative 0 problem on pnl values too:
https://github.com/delvtech/hyperdrive-frontend/pull/860/files
fixes #926

fixes negative value on lp apy

---

apps/hyperdrive-trading/src/network/constants.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useActiveToken.ts

This PR removes the option to deposit ETH in the Lido market. We don't want users losing their Sepolia ETH because they can't withdraw to native ETH in Sepolia Lido market. TODO's are commented where this logic will need to be removed for mainnet.
Closes #924 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/ab35c39d-e0c6-49be-9479-8e319de11cbd

Remove ETH Deposits for Lido

---

apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/network/wagmiClient.ts
yarn.lock

Latest version enables capsule on custom chains, so now we can add it regardless of the chain the frontend is configured for.
From Capsule team:
> Summary of changes from 0.7.0 -> 0.8.1
> * support custom chains in rainbowkit-wallet
> * 2FA defaults to disabled in react-sdk modal
> * fix for 2FA hanging on login in some cases

Upgrade capsule wallet to v0.8.1

---

apps/hyperdrive-trading/src/ui/base/components/PercentInput.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/token/SlippageSettings.tsx
apps/hyperdrive-trading/src/ui/token/TokenInput.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useSlippageSettings.ts
packages/hyperdrive-js-core/src/base/adjustAmountByPercentage.test.ts
packages/hyperdrive-js-core/src/base/adjustAmountByPercentage.ts

This PR adds a slippage settings menu to the token input form when opening a long. The form allows users to set an auto amount (0.5%), or a custom amount of slippage. 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/6a5305a9-f726-491c-985d-6ea84fcea6c3

Add slippage menu for open longs

---

packages/hyperdrive-js-core/src/base/testing/replaceBigIntsWithStrings.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.test.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

Value paid showing more than the bond amount, since this user open and closed this position once already at a loss and didn't make up the difference in the new position.
Same scenario, but since they fully closed the position, that resets the value paid and Fixed APR
This PR simplifies getOpenLongs by removing the **TransferSingle** events from the calculation. As a result, positions you transfer between wallets will not be visible in the UI at this time. This is for a few reasons:
- Previous support was untested and is currently unused
- The UI shows **value paid** and **profit/loss**, only available in OpenLong/CloseLong events
We do want to support `TransferSingle`-based positions. However, we'll need to consider how the UI will display these positions properly alongside …

Fix negative interest bug in getOpenLongs

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/token/SlippageSettings.tsx

This PR adds LP slippage adjustments the same way it does for Long and Short. The only difference is the adjustment is done on the lpSharePrice the user will receive. I've also added a tooltip prop to the settings component to clarify this difference a bit more.

Adds LP Slippage

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/CurrentValueCell.tsx

Closes #933 
This fixes a ui bug across all three position types. Sometimes the pnl can come back as a negative value near zero. In these cases we should show just zero in white font color. Previously, it was showing -0 in red as seen in the issue linked above.

Fixes misleading PNL label

---

packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.test.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

Related to the bug in #959 
Closes #972
This fixes the bug and adds a test for the case where you open a short, close it at a loss, then open it again in the same checkpoint.

Fix account bug in open Shorts table

---

apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTable.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx

Tighten up the landing page layout a bit so it's easier to read/scan
|Before|After|
|---|---|
|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/160fbfd4-006d-4936-97a2-50efa3f4c88f)|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/1f558040-6ca6-42a2-b79e-f7a50781c228)|

Fix widths of table and faq on All Markets page

---

apps/hyperdrive-trading/index.html
apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
package.json

Related to #977 
This PR adds logical groups to the market stats. In the next PR,I'll add the present value stat (aka: Total liquidity) under the Liquidity section.

Add groupings to Market Stats

---

apps/hyperdrive-sdk-docs/docs/sdk/index.md
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLiquidity.ts
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/useMarketRowData.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

Depends on https://github.com/delvtech/hyperdrive-bindings/pull/96
Related to #977 
Adding the ReadHyperdrive method for `getPresentValue` so we can display Total Liquidity in the All Markets table and in the market details pages.
While here I fixed a few spots where hyperwasm name had changed from our previous version. See #989 for original work.

Add `getPresentValue` to ReadHyperdrive

---

apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx

This PR separates the market impact and term into new sections in the OpenShortPreview:

separate market impact and term

---

apps/hyperdrive-trading/src/base/formatRate.test.ts
apps/hyperdrive-trading/src/base/formatRate.ts
apps/hyperdrive-trading/src/ui/app/Navbar/FeatureFlagPicker.tsx
apps/hyperdrive-trading/src/ui/base/components/Badge.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useImpliedRate.ts
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/PriceBadges.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
packages/hyperdrive-js-core/package.json
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/steth/ReadWriteStEthHyperdrive.ts
packages/hyperdrive-js-core/src/hyperwasm.ts
packages/hyperdrive-js-core/vite.config.ts
yarn.lock

This connects the `getImpliedRate` function from the new hyperdrive-wasm to both core-js and the frontend. 
Currently, a bug in the rust SDK's `calculate_implied_rate method` is returning incorrect values. I've placed this feature behind a flag until we resolve the issue described in https://github.com/delvtech/hyperdrive/issues/1003.
To view this feature, turn on the feature flag:

Upgrade hyperwasm to v0.13.0, add getImpliedRate to ReadHyperdrive, add stat to Yield section

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx

The amount of info on the LP card makes it hard to scan for things quickly. Adding logical groupings lets your eye skip over things to find the info you need.
Question: Is there a better label than **Your Position**?
|Before|After|
|---|---|
|<img width="1265" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/c11ac4a5-7e0c-4460-8574-9532505c9344">|<img width="1260" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/125cb182-1d15-4d41-9124-91e67f6b3faa">|

Add logical grouping to LP card

---

apps/hyperdrive-trading/src/hyperdrive/model/ReadHyperdriveModel.ts
apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/erc4626/ReadMockErc4626Hyperdrive.ts

This PR removes the getYieldSourceRate from ReadHyperdriveModel and places it in the SDK.

Move getYieldSourceRate into SDK

---

apps/hyperdrive-trading/src/hyperdrive/model/ReadWriteHyperdriveModel.ts
apps/hyperdrive-trading/src/hyperdrive/model/steth/ReadWriteStethHyperdriveModel.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useCloseLong.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useAddLiquidity.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRedeemWithdrawalShares.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRemoveLiquidity.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useCloseShort.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.tsx
packages/hyperdrive-js-core/package.json
packages/hyperdrive-js-core/src/evm-client/syncCacheWithTransaction.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadWriteHyperdrive.ts
packages/hyperdrive-js-core/src/index.ts
packages/hyperdrive-js-core/src/token/erc20/ReadWriteErc20.ts
packages/hyperdrive-js-core/tsconfig.json
packages/hyperdrive-viem/package.json
yarn.lock

This PR adds a new decorator to the hyperdrive-core-js package, `syncCacheWithTransaction`.
This decorator wraps any cached write contract method and listens for the tx to complete then invalidates the cache.

Add decorator for `syncCacheWithTransaction`

---

apps/hyperdrive-trading/src/ui/base/components/PercentInput.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/token/SlippageSettings.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useSlippageSettings.ts

Closes #1009 
This PR fixes the input validation bug that some users were experiencing on the slippage input. I've moved the input value to the type of string, and the conversion to bigint is done at the very end when we calculate the adjustment. This is similar to the pattern used in useNumericalInput where the values are kept as strings.
Before:
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/f3e302de-338f-47c0-8fec-bba700667e2a
After:
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/b70d9470-439a-46df-a3c7-6a54a6d17a2d

slippage bug fixed

---

apps/hyperdrive-trading/src/ui/hyperdrive/hooks/model/useReadHyperdriveModel.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useReadHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/metamorpho/ReadMetaMorphoHyperdrive.ts
packages/hyperdrive-js-core/src/index.ts
packages/hyperdrive-viem/src/hyperdrive/metamorpho/ReadMetaMorphoHyperdrive.ts
packages/hyperdrive-viem/src/index.ts

Add `ReadMetaMorphoHyperdrive` so we can implement getVariableRate in the sdk and consume it anywhere.

Fix bug causing morpho yield source apy to not show

---

apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
packages/hyperdrive-js-core/src/token/reth/ReadREth.ts

Adding a simple animation to help users draw the connection between the position types and their respective rates.
https://github.com/delvtech/hyperdrive-frontend/assets/4524175/b5ac3bcf-f8c2-47da-ac14-a6d45ca87fd3

Animate yield stat based on active position

---

Cargo.toml

Hyperdrive-wasm needs at least this version to compile correctly. 
You can upgrade to the latest version of rust by running `rustup update`
or checking your existing version with `rustup -V`.

Specify minimum rust compiler

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/FixedRateCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/AccruedYieldCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx

This PR right aligns some of stats in the position table. I've only done this for values where decimals could appear so the decimals will always be aligned vertically (see screenshots below). I couldn't rely on the standard `align-right` from tailwind here because of the way react-table maps over the data, as well as how it handles column widths.
Before Longs:
After Longs:
Before Shorts:
After Shorts:

Right align position table stats

---

apps/hyperdrive-sdk-docs/docs/sdk/guides/open-a-position.md
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.tsx

I had originally updated the adjustAmountByPercentage to handle floating point bigints, but there were a few points where we were not converting whole percentage numbers to their decimal alternatives. 
Co-authored-by: Danny Delott <DannyDelott@users.noreply.github.com>

Fix adjustAmountByPercentage decimals

---

apps/hyperdrive-trading/src/ui/app/Navbar/FeatureFlagPicker.tsx
apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
apps/hyperdrive-trading/src/ui/landing/Landing.tsx
apps/hyperdrive-trading/src/ui/landing/PositionCards/PositionCard.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTable.tsx
apps/hyperdrive-trading/src/ui/markets/Markets.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceCard/YieldSourceCard.tsx
apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx
packages/hyperdrive-appconfig/src/generated/11155111.appconfig.ts
packages/hyperdrive-appconfig/src/generated/31337.appconfig.ts
packages/hyperdrive-appconfig/src/generated/42069.appconfig.ts
packages/hyperdrive-appconfig/src/protocols/protocols.ts

Quick wireframe of the Tile layout for the All Markets page.
- We don't have room for another column
- Combining the Short APY into an existing column is weird too
- All Markets table contains a lot of duplicate information, creating visual noise the more pools we add
- (base asset + icon, yield source info, and Variable Rate... basically half of the table info).
- Grouping by yield source allows us to quickly find markets and choose a term.
- Duplicate info is "lifted up" into a single place on the tile
- Table on each tile only contains dynamic values a trader cares about
https://github.com/delvtech/hyperdrive-frontend/assets/4524175/e2111608-46e1-4df9-8ae9-cb5ddd4f0bc9

Tile layout for All Markets page

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useTotalLongsValue.ts
apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx

This PR adds a "Total Value" field to the top of the longs table. I created a new hook called useTotalLongsValue in order to make use of the `useQueries` hook. This way the queries get fetched in parallel, and they are saved to the cache so when the CurrentValueCell component calls it again in the table, it will already have access to the value.

Add total long value to long tab

---

apps/hyperdrive-trading/src/network/parseError.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useCloseLong.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useOpenLong.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useAddLiquidity.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRedeemWithdrawalShares.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useRemoveLiquidity.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useCloseShort.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useOpenShort.tsx

This PR adds error handling for errors that are returned by Viem. In a subsequent PR i'll address errors that get beyond this initial round of error checking, such as out of gas errors.
Question: @DannyDelott do we want to use that gradient branding text. It looks a little weird with the generic error. 
Also using toast.error is a bit strange because there are two x marks. I'm tempted to create a custom TransactionErrorToast component that removes the x mark on the left. Wdyt?

Adds custom error toasts on viem errors

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx

This is a PR that adds initial sorting to Long/Short tables to ensure your positions that are nearest to maturity show up at the top. There is still an existing issue where fully mature positions are showing up at the bottom. I think the best UX is to show these at the top so i'll investigate a custom sorting function on Monday.
I'll also add this sorting to the closed tables in a separate PR. Where recently matured positions will show up at the top.

adds maturity date sorting

---

apps/hyperdrive-trading/README.md
apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useMarketState.ts
apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModalButton.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useMintToken.tsx

We shouldn't need to depend on the abis for anything, that's what the sdk and appconfig are for.

Remove dependency on hyperdrive artifacts in trading ui

---

apps/hyperdrive-trading/src/ui/base/mediaBreakpoints.ts
apps/hyperdrive-trading/src/ui/markets/YieldSourceCard/YieldSourceCard.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx

Related to #1038 
This renders a mobile table for any breakpoint that's < tailwind `sm` breakpoint.

Mobile layout for new market cards

---

apps/hyperdrive-trading/src/ui/base/components/WarningButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortModalButton/OpenShortModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTable.tsx
apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx

This PR adds a warning label to the market tabs and nonideal state if the marketstate is currently paused. If the user currently has positions open, a warning label is presented in the tab bar and the open position button is removed. The user will still be able to remove any open positions. If the user has no positions open the buttons are removed all together and the market paused info is presented in the non-ideal state.
I'm trying to decide if I should add the warning button to the non-ideal state or if the text is sufficient. Thoughts @DannyDelott?

Adds market paused button

---

apps/hyperdrive-trading/src/ui/landing/PositionCards/PositionCard.tsx
apps/hyperdrive-trading/src/ui/onboarding/FAQ/FAQ.tsx

`text-neutral-content` is just too blueish to be used for lots of text. Switching to `opacity-80` in the FAQ and How it Works cards makes things less eye straining

Color polish

---

.changeset/blue-plants-play.md
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/useRowData.ts
apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/metamorpho/ReadMetaMorphoHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/steth/ReadStEthHyperdrive.ts

Fixes #1074.
This PR updates `getYieldSourceRate` to stop using `getRate()` on the mock contract, which only works on testnet. Instead, it switches to a calculation based on hyperdrive state, making it chain-agnostic and compatible with any yield source.
Additionally, I eliminated the specific logic for fetching the Lido Steth rate from their official web API, introduced in #1071. Similarly, I removed the method for retrieving the Morpho Dai rate from a fabricated snippets contract deployed to Sepolia.

Compute the yield source rate from Hyperdrive state

---

.changeset/great-apes-hug.md
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

Closes #935 
New hyperwasm function call:
Current simulate call on testnet:

Replace add liquidity simulate with hyperwasm 

---

apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

Showing the max trades in the stat and relabeling it to "idle liquidity" to be more descriptive.

Show max trades in available liquidity stat, improve Insufficient Liquidity error message

---

apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/vaults/YieldSourceRateBadge.tsx

This PR fixes the tooltips on market stats and cleans up the mobile layout. @DannyDelott one thing we should keep in mind going forward is if we update the layout on a component that has a tooltip, it might impact the mobile layout. Since the daisy ui tooltip isn't screen-size aware, it can add a bunch of padding where the tooltip is supposed to appear. 
Before:
After:

Fix tooltips and mobile layout

---

apps/hyperdrive-trading/src/ui/app/Footer/Footer.tsx

Instead of having 1 tall column on our mobile footer, I think it looks nicer to split it into two. 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/22f30196-144e-4d91-9659-991bb060dc57

Cleanup footer

---

apps/hyperdrive-trading/src/ui/app/Navbar/FeatureFlagPicker.tsx
apps/hyperdrive-trading/src/ui/base/components/MultiStat.tsx
apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/base/components/TabbedStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketDetailsBody.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/FixedRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/ShortRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx

Adding the ability to show the rate as both an APR or an ROI.
This is currently just the skeleton of the components. It's behind feature flag so folks can start playing with the UX.
In the next PR I will upgrade us to the latest hyperdrive-rs, which will allow us to do the conversions between rates.
https://github.com/delvtech/hyperdrive-frontend/assets/4524175/986f1940-9b32-4524-9dac-f8ac011afbc3

Add MultiStat component, add feature flag for apr and roi switching

---

apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/ShortRateCell.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/useRowData.ts

Moving the Short Rate into its own component lets us still show the pools, while we figure out why short rate isn't calculated correctly:

Fix pools not showing for ezeth

---

apps/hyperdrive-trading/src/ui/token/hooks/useTokenBalance.ts
apps/hyperdrive-trading/src/vaults/isReth.ts
crates/hyperdrive-wasm/src/long/close.rs
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/reth/ReadREthHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/steth/ReadStEthHyperdrive.ts
packages/hyperdrive-js-core/src/hyperdrive/steth/ReadWriteStEthHyperdrive.ts

Related to #1066.
- The `ReadStEthHyperdrive` model, which is responsible for converting amounts from Lido shares to stETH, was missing `getMaxLong` and `getMaxShort` overrides to convert the `maxSharesIn`.
- The `ReadWriteStEthHyperdrive` model wasn't converting any of the stETH amounts to Lido shares, so transactions were being submitted with higher share amounts than what the UI showed.
All missing conversions were added.
- The `MockLido` and `MockRocketPool` contracts [calculate share price based on the current timestamp](https://github.com/delvtech/hyperdrive/blob/main/contracts/test/MockLido.sol#L171) which means that the accuracy of any calculations based on share price will slowly drift as time passes. This was causing errors when trying to open the max long/short since the max …

Add missing stETH conversions, temp patches for `MockLido` & `MockRocketPool` shares accounting

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
packages/hyperdrive-appconfig/src/generated/11155111.appconfig.ts
packages/hyperdrive-appconfig/src/yieldSources/YieldSourceTokenConfig.ts
packages/hyperdrive-appconfig/src/yieldSources/extensions.ts

Since the stEth amount is essentially a baseAmount, we don't need to do a convertSharesToBase if we are on a steth market. This PR just checks if we are on a steth market and passes the baseAmountPaid instead of a converted amount. This closes #1114

fix steth conversion bug on OpenLongPreview

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewOpenLong.ts

This PR refreshes the open long preview data on each new block. I use the wagmi hook to watch for new blocks, and then add it to the query key so the data revalidates. I'll do this next for shorts and LP. 
Note: It isn't actually this slow refetching. I throttled the network to show the skeleton.
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/e1f41a8f-68b6-4d6b-a3da-85d85cb0ae85

Refresh preview data on new block

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewOpenLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/usePreviewOpenShort.ts

This PR refetches the short preview data on new blocks. Below is a screenshot of what the 'fetching' state looks like on the preview.

refetch short data on new block

---

.changeset/config.json
.changeset/sixty-lobsters-give.md
packages/hyperdrive-viem/package.json

Fixes #1137 
This should ensure that a new version of `@delvtech/hyperdrive-viem` is released alongside every new version of `@delvtech/hyperdrive-js-core`. The release type (patch, minor, or major) will match that of core. I would have liked to keep these at version `0`, but `@delvtech/hyperdrive-js-core` was bumped passes major version `0` unfortunately.
See: https://github.com/changesets/changesets/blob/main/docs/linked-packages.md#example-with-dependants

Link `hyperdrive-js-core` and `hyperdrive-viem` versions.

---

apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewCloseLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/usePreviewCloseShort.ts

Related to #1144 
This adds the warning icon w/ tooltip on the Shorts table.
Some things of note:
- Tanstack's default `retry` behavior is not a fit for our previewCloseShort hook. If the sdk method fails, no amount of retrying will fix the issue, as it's indicative of bad inputs...not a network problem. 
- I've turned this off in this hook so that it quiets down the console significantly, gives the error back to the user almost immediately, and prevents unwanted skeleton flickering.

Show warning on Current Value cell when no value exists

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewCloseLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/CurrentValueCell.tsx

Related to #1144 
Related to #1149 (<-- implemented this functionality for shorts)
This PR shows a warning on the Current Value cell for Longs when the can't be fully closed.

Show warning on Current Value cell when no value exists (Longs)

---

.changeset/pink-pans-drop.md
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useShortRate.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

We were passing the wrong vaultSharePrice to `calculate_close_short`. Instead of using the current vaultSharePrice, we need to be using the price from the checkpoint in which the position was created.
This fixes the issue where a mature position looked like it couldn't be closed.
|Before|After|
|---|---|
|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/daddb78a-1649-462a-99c9-d6334d27f834)|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/9d4f0540-acd3-4fb8-96f8-22ee5223f52a)|

Fix incorrect openVaultShare price on previewCloseShort

---

apps/hyperdrive-trading/src/network/queryClient.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewCloseLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/usePreviewCloseShort.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useShortRate.ts

Finding myself doing this a few times now, and I think it's safe to just turn off globally. 
If we need to set a retries for a specific query that's totally fine. We do this in place already, in `useAddressScreen`, where a  custom `retries: 6` is set.

Don't retry queries

---

apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/ShortRateCell.tsx
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

We had a comparison operator that was flipped, causing Current Value to show `0` on shorts that were just minted.
While here, I also added red/green coloring to the Short APR on the main page. This is for a few reasons:
- The **fixed rate** can't go negative, so the gradient helps show that it's impervious to "going into the red"
- The short rate _can_ go negative, so when scanning the markets it's nice to immediately see which pools have profitable short sides.  
Comparing the before and after, it's much easier to find profitable markets with the coloring:
|Before|After|
|---|---|
|<img width="1729" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/6afd3310-4098-45af-85ee-6a03090af9e1">|<img width="1738" alt="image" …

Fix bug causing current value in open shorts to display 0, polish Yield Source Market cards

---

apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx

Show the effective short apr the user is getting once they open the short. Closes #1143

Show effective short apr in preview

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableMobile.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableMobile.tsx

While investigating a straggling ⌄ icon on mobile tables, I realized we aren't using the `<tableheader/>` at all and just rendering the labels in the cell itself. I've removed the table header for now. But in the near future we will probably want to have a mobile table filtering/sorting menu. React Table should make this straight forward and i've added an issue for it:
https://github.com/delvtech/hyperdrive-frontend/issues/1185

remove unused tableheader on mobile

---

apps/hyperdrive-trading/src/ui/base/components/Stat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/MaturesOnCell/MaturesOnCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/getRemainingTimeLabel.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongModalButton/CloseLongModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortModalButton/CloseShortModalButton.tsx

Followup to #1181 
- Fix wrapping by condensing labels that include both hours and minutes
- Polish Term Complete badge in close long and close short
- Code cleanups to props

Polish open and close position modals

---

apps/hyperdrive-trading/README.md
apps/hyperdrive-trading/src/routeTree.gen.ts
apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
apps/hyperdrive-trading/src/ui/bridge/Bridge.tsx
apps/hyperdrive-trading/src/ui/bridge/routes.ts
apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
apps/hyperdrive-trading/src/ui/routes/bridge.tsx
packages/gopher/.eslintrc
packages/gopher/.gitignore
packages/gopher/.prettierignore
packages/gopher/.prettierrc.js
packages/gopher/LICENSE
packages/gopher/README.md
packages/gopher/out/gopher.ts
packages/gopher/package.json
packages/gopher/src/api.ts
packages/gopher/src/gopher.json
packages/gopher/tsconfig.build.json
packages/gopher/tsconfig.json
yarn.lock

Adds the `/bridge` route to the app under the 'bridge' flag.
Adds a basic packages/gopher with generated typescript api for gopher's swagger api.

Add gopher package and /bridge route

---

apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/FixedRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/ShortRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx

Makes reading the Yield rates more intuitive by coloring negative Short rates in red.

Display Negative Short APR/ROI in Red in Yield Stats

---

apps/hyperdrive-trading/src/ui/base/components/LabelValue.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityPreview/AddLiquidityPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx

This round of polish solves the issue where Preview Transaction values each had a different UI treatment to try and make it stand out. In doing so, none of them stood out.  See comments in #1181 
To solve this we move tooltipping off of the value and onto the label, eliminating the underlining treatment and making those numbers easier to read at the same time.
|Before|After|
|---|---|
|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/7c30e813-0246-4486-bcb3-b40daf582355)|<img alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/01b4d490-7d34-42a6-9d6c-dbb1d3b2b14a">|

Polish Preview Transaction sections in open position modals

---

apps/hyperdrive-trading/src/ui/base/components/Tabs/Tabs.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/TransactionsTable.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/TransactionTable/useTransactionData.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useMaxLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewOpenLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityPreview/AddLiquidityPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useMaxShort.ts
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/TransactionsAndFaqTabs/TransactionsAndFaqTabs.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useApproveToken.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useTokenAllowance.ts

It's nice to see your transaction history separate from everyone else's in the pool. This PR adds a new tab to show just your trades.

Add Your Transactions table to market details

---

apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/base/components/ConnectWallet.tsx
apps/hyperdrive-trading/src/ui/base/components/VersionPicker.tsx

This PR cleans up the Navbar:
1. Removes primary color used in the ConnectWallet button if the user is already connected. I think we should save that green color for actions we want the user to take, Connect Wallet, Open Long. If the wallet is already connected no further action is needed.
2. The chain name is replaced with the chain icon and joined with the connect wallet button.
3. A version picker is placed behind a feature flag and this replaces the "Cast on Warpcast" button. 
https://github.com/delvtech/hyperdrive-frontend/assets/22210106/93d1f397-7fcd-499a-8226-bd35c5df81e2

Navbar Cleanup

---

apps/hyperdrive-trading/src/ui/base/components/Modal/Modal.tsx
apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsForm.tsx
apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsModal/BridgeAssetsModal.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModal/OpenLongModal.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx

This PR does the minimum to let us switch modal UIs.  I copied code from the OpenLongModal for now so we can see how it looks.  Next step will be fill out the logic for the `<BridgeAssetsModalForm />`.
- add ui to switch to bridge modal
- refactor OpenLongModal
- add BridgeAssetsModal
- allow multi modal mode
- toggle between modal uis

add ui to switch to bridge modal

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/LpApyCell.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx

This PR adds a shiny ✨ New text to the lpapi if no data is available. One additional thing we could add is a tooltip to explain why there is no data.

adds new text to lpapy

---

crates/hyperdrive-wasm/src/lib.rs
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

The present value calculation was wrongly documented as returning the result in base. This PR corrects the documentation and updates the SDK to convert the present value from shares to base.
|Before|After|
|---|---|
|![image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/9f10d0c2-c49c-4cc4-8a6d-5aef5accaeca)|<img alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/77a7351d-a856-480c-855d-e810a0cd7449">|

Convert present value to base amount

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/withdrawalShares/RedeemWithdrawalSharesForm/RedeemWithdrawalSharesForm.tsx
packages/hyperdrive-js-core/src/base/adjustAmountByPercentage.ts

Related to #1226 
This sets a 0.5% threshold for removing liquidity and a 2% threshold for redeeming withdrawal shares.

Improve default values for minOutputPerShare

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx

This PR sets the rate guards (`minApr` and `maxApr`) for adding liquidity to +/- 2% of the current fixed rate. 
This prevents LPs from entering into a situation where the fixed rate spikes between the time they submit their tx to add liquidity and when the tx is ultimately mined. Adding liquidity when the fixed rate is significantly higher than the variable rate is bad for LPs.
Closes #1228

Improve the default minApr and maxApr for Add Liquidity

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/usePreviewAddLiquidity.ts

We use hyperwasm now for the previewAddLiquidity, but were still checking allowances. This PR makes it so you can get a tx preview without approving anything first.

Don't require allowance for previewing Add Liquidity

---

apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/ShortRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/ShortRateCell.tsx

Tuning this better, since 1e18 is a whole eth, which doesn't work well when the steth pool is low on idle liquidity

Update short rate preview size to 1e15 instead of 1e18

---

apps/hyperdrive-trading/src/ui/base/components/Modal/Modal.tsx
apps/hyperdrive-trading/src/ui/token/TokenInput.tsx

The Modal component needs an onClose listener for upcoming bridging UI.  Mainly want to make sure that we can reset the modal to the default open long ui when it closes.
Also added a small css tweak to TokenInput to allow it to grow when its contents are larger than w-64.

add onClose to `Modal`, use min-width for `TokenInput`

---

apps/hyperdrive-trading/src/registry/data.ts
apps/hyperdrive-trading/src/ui/chainlog/FactoriesTable.tsx
apps/hyperdrive-trading/src/ui/chainlog/PausedCell.tsx
apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx
apps/hyperdrive-trading/src/ui/chainlog/StatusCell.tsx

Add a "Status" column to the chainlog tables and some utils for decoding registry data. The utils are added to the UI rather than the SDK because the encoding is specific to the ElementDAO's registry. Another deployment could use a different schema.
closes #1120

Add status column to chainlog

---

packages/hyperdrive-js-core/src/fixedpoint.ts
packages/hyperdrive-js-core/src/hyperdrive/ReadHyperdrive/ReadHyperdrive.ts

h/t @Ryan for the fixedpoint wrappers!
This fixes #1244 by changing getYieldSourceApy calc to use the compounding formula.

fix getYieldSourceApy to use compounding formula

---

apps/hyperdrive-trading/src/base/formatRate.test.ts
apps/hyperdrive-trading/src/base/formatRate.ts

Refactor formatRate to use d3-format instead of toLocaleString(). This fixes an issue where users were seeing weird rate formatting, (they use `,` instead of `.` in other languages)

Fix bug causing incorrect formatting of rates

---

apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/markets/AllMarketsTable/AllMarketsTableMobile.tsx
apps/hyperdrive-trading/src/ui/markets/LongsShortsLpTabs/LongsShortsLpTabs.tsx
apps/hyperdrive-trading/src/ui/markets/LongsTab/LongsTab.tsx
apps/hyperdrive-trading/src/ui/markets/LpTab/LpTab.tsx
apps/hyperdrive-trading/src/ui/markets/Market.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/OpenClosedFilter/OpenClosedFilter.tsx
apps/hyperdrive-trading/src/ui/markets/ShortsTab/ShortsTab.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableMobile.tsx
apps/hyperdrive-trading/src/ui/markets/hooks/useOpenOrClosedSearchParam.tsx
apps/hyperdrive-trading/src/ui/routes/market.$address.tsx

- Removes the `loader` and `loaderDeps`.
- Makes search params optional to avoid needing to explicitly set them in every link.
- Makes search params lowercase.

Simplify `/market/$address` route

---

apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/ui/compliance/hooks/useAddressScreen.ts
apps/hyperdrive-trading/src/ui/compliance/hooks/useVpnScreen.ts

For some reason, the `fixed-point-wasm` version didn't get bumped in the changesets PR, so this bumps it manually and addresses review comments I missed in my last PR.

Fix FE dependency

---

apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/TransactionView.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModal/OpenLongModal.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx

This PR fixes some of the spacing on the primary stats. A couple more details are aligned with the design in the figma. Removing the close modal button and updating some copy. There is some additional padding around the modal, but I think it's okay to leave this until all the position forms are updated and we can fix it all at once in the modal component.

Fix primary stat spacing

---

apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityModalButton/AddLiquidityModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/FixedRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/ShortRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/ShortRateCell.tsx
apps/hyperdrive-trading/src/ui/markets/YieldSourceMarketsTable/YieldSourceMarketsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/vaults/YieldSourceRateBadge.tsx

This PR removes the extra percentage sign as the sign is already provided by fixed-point-wasm! I'm pretty sure I got them all but let me know if you see any others.
Before:
After:

Remove double percantages

---

apps/hyperdrive-trading/src/ui/token/SlippageSettingsTwo.tsx

I have no idea why the daisy-dropdown menu is starting open when the modal is opened. This is a quick fix so that we can get a release out today. We tend to avoid useState for these things but I've tried a few other methods that rely on built in daisy functionality and it hasn't worked.

dropdown starting closed

---

packages/hyperdrive-js-core/src/hyperdrive/base/ReadHyperdrive.ts

Reverts a change made in #1306.
My `biome` extension was enabled when I started the PR and showing errors about using `forEach` over `for..of`, so I ran the format fix to see if the changes would be minor. They weren't, so I reverted the changes and disabled the extension, but these `break`s snuck in some how.

Replace `break` with `return` in `forEach`

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/LiquidityStats.tsx

For the rETH pool, the max long and max short we're displaying properly (`0.0` instead of `0.0022`)

Show values to their given places

---

apps/hyperdrive-trading/src/base/formatRate.ts
apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLpApy.ts
packages/hyperdrive-js-core/src/hyperdrive/base/ReadHyperdrive.ts

LP APY and Variable APY differ significantly from each other, even in markets with no open long/short positions.
LP APY looks at `lpSharePrice` on a checkpoint-by-checkpoint basis, within a 7-day timeframe.
Yield Source APY looks at `vaultSharePrice` on a block-by-block basis, within a 2-day timeframe.
This difference in methods and time frames results in different rates.
This PR changes both to update on a block-by-block basis, within a 1-day timeframe

Change vaultApy and lpApy to use the same calculation method

---

apps/hyperdrive-trading/src/ui/bridge/BridgeAssetsForm/BridgeAssetsForm.tsx
packages/hyperdrive-appconfig/src/appconfig/getAppConfig.ts
packages/hyperdrive-appconfig/src/generated/1.appconfig.ts
packages/hyperdrive-appconfig/src/generated/11155111.appconfig.ts
packages/hyperdrive-appconfig/src/hyperdrives/HyperdriveConfig.ts
packages/hyperdrive-appconfig/src/hyperdrives/custom/getCustomHyperdrive.ts
packages/hyperdrive-appconfig/src/hyperdrives/morpho/getMorphoHyperdrive.ts
packages/hyperdrive-appconfig/src/hyperdrives/steth/getStethHyperdrive.ts
packages/hyperdrive-appconfig/src/tokens/getTokenConfig.ts

This adds a `chainId` field on `HyperdriveConfig` and `TokenConfig`, making it possible to store multi-chain hyperdrives in a single appconfig.
Related to #1356 but going to land this in multiple parts. Closes #1355

Add chainId field to HyperdriveConfig and TokenConfig

---

apps/hyperdrive-trading/src/network/wagmiClient.ts
apps/hyperdrive-trading/src/wallets/capsule.ts

This makes it so you don't have to configure env variables for Capsule to run the frontend.

Omit Rainbowkit options for capsule if no .env for it

---

apps/hyperdrive-trading/src/ui/bridge/Bridge.tsx

using the iframe approach for now until the issues with the v2 and v3 squid widget are solved.  this is the v2 iframe, here's a screenshot:
here's the [link](https://v2.widget.squidrouter.com/iframe?config=%7B%22integratorId%22%3A%22squid-swap-widget-v2%22%2C%22companyName%22%3A%22Squid%22%2C%22style%22%3A%7B%22widgetContainer%22%3A%7B%22className%22%3A%22squid-widget-animated-container%22%7D%2C%22neutralContent%22%3A%22%23ffffff%22%2C%22baseContent%22%3A%22%23ffffff%22%2C%22base100%22%3A%22%231a272c%22%2C%22base200%22%3A%22%2311191d%22%2C%22base300%22%3A%22%23000000%22%2C%22error%22%3A%22%23ED6A5E%22%2C%22warning%22%3A%22%23FFB155%22%2C%22success%22%3A%22%232EAEB0%22%2C%22primary%22%3A%22%2318ffab%22%2C%22secondary%22%3A%22%2318ffab%22%2C%22secondaryContent%22%3A%22%23F7F6FB%22%2C%22neutr …

add squid-route-v2 widget

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktopTwo.tsx

This PR adds an APR label to the longs table. It also simplifies the loading state on the portfolio longs table. Before we were using the deprecated `useOpenLongs` on each table to fetch data we had already fetched at the top level using `usePortfolioLongsData`. Now we just wait for the one `openLongPositionsStatus` and then render all the tables.  See below for before and after:
Before:
https://github.com/user-attachments/assets/a566ab42-bfee-4620-aa6b-5cf4a3f49ab5
After:
https://github.com/user-attachments/assets/91dc8b37-1c41-4b87-9815-da30f2c87cc4

Simplifies Loading State, adds APR Label

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongModalButton/CloseLongModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortModalButton/CloseShortModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/withdrawalShares/RedeemWithdrawalSharesForm/RedeemWithdrawalSharesForm.tsx
apps/hyperdrive-trading/src/ui/markets/AssetStack.tsx
apps/hyperdrive-trading/src/ui/markets/MarketDetailsBody/MarketHeader.tsx
apps/hyperdrive-trading/src/ui/markets/YourBalanceWell/YourBalanceWell.tsx
packages/hyperdrive-appconfig/src/hyperdrives/selectors.ts
packages/hyperdrive-appconfig/src/tokens/selectors.ts

Tokens can have the same address on different chains, so this selector now takes the `chainId` as a required parameter.

Add `chainId` to findToken selector

---

apps/hyperdrive-trading/src/ui/markets/MarketStats/VariableRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx

Yield stats now show the Variable APY instead of the short rate.

Show variable apy instead of short rate in Yield stats

---

apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/ui/chainlog/FactoriesTable.tsx
apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx
packages/hyperdrive-appconfig/package.json

Fixes the factories tab by using all chain ids from `appConfig.registries` rather than assuming there's a registry for each chain.

Use `registries` instead of `chains` for chainlog chain ids

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/token/TokenPicker.tsx
apps/hyperdrive-trading/src/ui/token/TokenPickerTwo.tsx

The token icons may not be round by default. When used in Daisy avatar components, the rounding is automatically applied. However, for instances where we use img tags, we need to manually apply the rounding to ensure consistent appearance.

Fix rounding icons

---

.changeset/ninety-queens-walk.md
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLpApy.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
packages/hyperdrive-js-core/src/hyperdrive/base/ReadHyperdrive.ts

Making this more consistent with our our other rates, this now returns a bigint from the SDK. The frontend now uses the same pattern for rate hooks. (see todo that was removed)

Return bigint for `getLpApy`

---

apps/hyperdrive-trading/src/network/wagmiClient.ts

This ensures mainnet is the default chain used for unconnected users or users without wallet extensions.

Move `mainnet` to first chain in `wagmiConfig`

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktopTwo.tsx

This PR removes the clickability for the entire row in the portfolio page. This is in favor of the manage button.

Remove portfolio row clickability

---

.changeset/clean-phones-trade.md
apps/hyperdrive-trading/src/ui/hyperdrive/lp/LpAndWithdrawalSharesTable/LpCurrentValueCell.tsx
packages/hyperdrive-js-core/src/hyperdrive/base/ReadHyperdrive.ts

This PR updates ReadHyperdrive to Include the base value of withdrawal shares received when recalculating baseAmountPaid for _calcOpenLpPosition. Also the calc is updated on the frontend to reflect the correct profit/loss for both partially and fully withdrawable lp.

Fix math on LP Current Value Cell

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongModalButton/OpenLongModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/OpenLpSharesCard/OpenLpSharesCard.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortModalButton/CloseShortModalButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortModalButton/OpenShortModalButton.tsx
apps/hyperdrive-trading/src/ui/token/RevokeAllowanceModalButton.tsx

User was seeing the following error when going to the pool details page. This comes from trying to call `close()` on the modal dom node, which may not exist yet.

Fix error in modal closing behavior

---

apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useLpApy.ts
apps/hyperdrive-trading/src/ui/markets/MarketStats/VariableRateStat.tsx
apps/hyperdrive-trading/src/ui/markets/MarketStats/YieldStats.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts

The number of days we display for LP APY is now based on either the full rate period (if we have enough history) or the maximum days we have.
Below you can see that the `Ether.fi Staked Eth` pool is now reflecting a more accurate `20d` period, than the pre-set `30d`.
New vs Old

Show the correct number of days when pool is younger than rate period

---

apps/hyperdrive-trading/src/base/assertNever.ts
apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip.tsx
apps/hyperdrive-trading/src/ui/rewards/useRewards.ts

Adding a RewardType for Linea's XLP-L rewards and whitelisting the linea rsesth pool.

Add rewards for linena rseth

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/token/TokenInputTwo.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useTokenFiatPrice.ts

Similar to uniswap, if the user hasn't input anything we don't need to show the Transaction Details accordion.

Don't show transaction details when inputs are empty

---

apps/hyperdrive-trading/src/ui/hyperdrive/InvalidTransactionButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx

Moving our disclaimers into disabled buttons instead. This looks much nicer and avoids a layout shift:
|Long|Short|Supply|
|---|---|---|
|<img width="619" alt="image" src="https://github.com/user-attachments/assets/41a36af5-e16a-4a09-913d-f4b0da5a4119">|<img width="558" alt="image" src="https://github.com/user-attachments/assets/219a7b70-f2e1-4d6b-96e8-1fc511ebf9a7">|<img width="570" alt="image" src="https://github.com/user-attachments/assets/1fa28427-dd57-4738-86a1-1e331c1f23e3">|

Move disclaimers into buttons

---

apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
apps/hyperdrive-trading/src/ui/markets/PoolDetails/PoolDetails.tsx
apps/hyperdrive-trading/tailwind.config.js

[Hyperdrive---DeFi-Yield-your-way (2).webm](https://github.com/user-attachments/assets/d6ac4aff-5828-418f-afb3-f6b4225d1209)

Add an animated border to Pool Row card

---

apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolsList.tsx

Adding everything directly to the `PoolsList` component for now. If the component get's too unruly after all the list controls are added, we can break it down.

Add chain filter to pools list

---

apps/hyperdrive-trading/src/hyperdrive/calculateMarketYieldMultiplier.ts
apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx

This PR changes the variable apy on the all pools page to be the default yield multiplier for opening a short. Also, this default multiplier is added to the primary stat when you visit the OpenShortForm and haven't typed anything in yet.
I will update the sorting of the PoolRows to include the multiplier once the more general refactor of sorting is done.
Closes #1509

Add default Yield Multiplier to PoolRow and OpenShortForm

---

apps/hyperdrive-trading/src/ui/landing/Landing.tsx
apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx
apps/hyperdrive-trading/src/ui/routes/index.tsx

The pool filter state is now stored in the URL. This allows you to refresh the page or use the Back button from a pool details page, and still see the same list of filtered pools.
[Hyperdrive---DeFi-Yield-your-way (3).webm](https://github.com/user-attachments/assets/dcb06e3e-7ad1-49ba-9cb5-8520f07df72f)

Persist pool filters in route

---

apps/hyperdrive-trading/src/routeTree.gen.ts
apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/chains/SwitchChainButton/SwitchChainButton.tsx
apps/hyperdrive-trading/src/ui/markets/routes.ts
apps/hyperdrive-trading/src/ui/mint/MintView.tsx
apps/hyperdrive-trading/src/ui/mint/routes.ts
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
apps/hyperdrive-trading/src/ui/portfolio/routes.ts
apps/hyperdrive-trading/src/ui/routes/mint.tsx
apps/hyperdrive-trading/src/ui/routes/portfolio.tsx

Add a route item to the navbar when on testnet to take you to a Mint Tokens page, where you can mint any of the tokens available in the testnet appconfig.
Closes #1560
[Hyperdrive---DeFi-Yield-your-way (5).webm](https://github.com/user-attachments/assets/75f0a105-da38-4539-9f61-754d3e48d8cf)

Add mint route, wire up mint buttons

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/ManageLongsButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktopTwo.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/LpAndWithdrawalSharesTable/LpAndWithdrawalSharesTable.tsx
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx

This PR adds a manage dropdown for existing long positions allowing users to either open a new long in this market, or close the current one. 
https://github.com/user-attachments/assets/07174ea3-0b45-405e-aaba-c1aa8d544ce1
Closes #1567

Add Manage dropdown for longs

---

apps/hyperdrive-trading/src/network/wagmiClient.ts

when connecting via gnosis safe app the injected connector is taking priority. My guess is it's because of the order of the list which this rainbow-kit section suggests  [// needs to be first](https://www.rainbowkit.com/docs/custom-wallet-list#injected-wallet)

Reorder wagmi wallets list

---

apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/RemoveLiquidityForm/RemoveLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/CloseShortForm/CloseShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/YieldMultiplierCta.tsx
apps/hyperdrive-trading/src/ui/token/SlippageSettings.tsx
apps/hyperdrive-trading/src/ui/token/SlippageSettingsTwo.tsx
apps/hyperdrive-trading/src/ui/token/TokenInputTwo.tsx

Add `"formChange"` Plausible event, remove `"slippageChange"`

---

apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/ManageShortButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/OpenShortsTableDesktopTwo.tsx

Update manage short button to dropdown

---

apps/hyperdrive-trading/src/base/formatRate.test.ts
apps/hyperdrive-trading/src/base/formatRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useFixedRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm2.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/LpAndWithdrawalSharesTable/LpCurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortsTable/ShortRateAndSizeCell.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useShortRate.ts
apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyStat.tsx
apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts

Convert positional arguments into an options object and remove unnecessary `decimals` parameter (all apys/aprs/percentages are to be provided as an 18-decimal number)

Cleanup `formatRate` util

---

apps/hyperdrive-trading/src/hyperdrive/getLpApy.ts
apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/rewards/useRewards.ts
packages/hyperdrive-appconfig/src/index.ts
packages/hyperdrive-appconfig/src/rewards/selectors.ts

Adds a selector to prevent directly accessing the `rewardsFunctions` object.
While here I noticed that the `YieldSourceId` type does not work outside of the appconfig package, so for now the id argument to the `getRewardsFn` is typed as `string`. See #1637 for more info.

Adds selector for getRewardsFn

---

apps/hyperdrive-trading/src/ui/chainlog/FactoriesTable.tsx
apps/hyperdrive-trading/src/ui/chainlog/PoolsTable.tsx

This refactors the chainlog pools table query to use `Promise.all()` and `.then()` chaining which reduced the number of requests from **87** to **17**, and the data transfer from **36.6 kB** to **12.6 kB**.

Optimize chainlog

---

apps/hyperdrive-trading/src/hyperdrive/getLpApy.ts
apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/usePrepareSharesIn.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/usePrepareSharesOut.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/LpAndWithdrawalSharesTable/ManageLpAndWithdrawalSharesButton.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/PoolDetails.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
packages/hyperdrive-appconfig/package.json
packages/hyperdrive-appconfig/src/hyperdrives/HyperdriveConfig.ts
packages/hyperdrive-appconfig/src/hyperdrives/selectors.ts
packages/hyperdrive-appconfig/src/index.ts
packages/hyperdrive-appconfig/src/rewards/selectors.ts
packages/hyperdrive-appconfig/src/yieldSources/base.ts
packages/hyperdrive-appconfig/src/yieldSources/gnosis.ts
packages/hyperdrive-appconfig/src/yieldSources/linea.ts
packages/hyperdrive-appconfig/src/yieldSources/mainnet.ts
packages/hyperdrive-appconfig/src/yieldSources/types.ts
packages/hyperdrive-appconfig/src/yieldSources/yieldSources.ts
yarn.lock

Closes #1637 
This creates a `YieldSourceId` that is strongly typed, avoids circular dependencies in appconfig, and can be used in consumer code without the type getting lost, as we found to be the case when using declaration merging with `tsup`.
While here I also added a `findYieldSource` selector to centralize the way we lookup this info in appconfig. This will make it easy to restructure appconfig as needed without needing to update all the consumers.

Refactor declaration merging to type union, add yieldSource selector

---

apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx

Closes #1652 
These two pools use a baseTokenFallback to calculate TVL, but we were calling the priceOracle function with the poolConfig's baseToken which is set to the zero address.

Fix missing TVL on cbETH and wstETH

---

apps/hyperdrive-trading/src/ui/markets/PoolsList.tsx

Based on discussions in Discord, we're removing this pool for now.

Remove mainnet morpho susde/dai from All Pools list

---

apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx

This PR ensures all values and valueUnits are aligned to a single baseline and wrapped properly. It also ensures consistency in font sizes for all value units with the exception of the short multiplier. 
See design:
https://www.figma.com/design/zyvr6cjxpcXZlrQJCrBrpy/Hyperdrive-Trading-UI?node-id=88-12&m=dev&t=iT6zj1ywQXQYuOhN-1
Closes #1563

ensure primary stat text aligned to baseline

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useTotalOpenLpPositions.ts
apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesContainer.tsx
apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesTable/LpAndWithdrawalSharesTable.tsx
apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesTable/TotalLpValue.tsx
apps/hyperdrive-trading/src/ui/portfolio/lp/usePortfolioLpData.ts

This PR refactors the Open LP position tables on the portfolio to take an array of Hyperdrives grouped by yield source. Previously, each Hyperdrive instance rendered one table with one row if there was an open LP position. By grouping these positions by yield source we can add open position totals to the top of each table.

Group Open LP Positions by Yield Source and Chain Id

---

apps/hyperdrive-trading/src/hyperdrive/getLpApy.ts
apps/hyperdrive-trading/src/ui/analytics/Plausible.tsx
apps/hyperdrive-trading/src/ui/markets/PoolDetails.tsx
apps/hyperdrive-trading/src/ui/portfolio/rewards/useRewardsData.ts

Related to #1669 
This adds some basic info about the pool so that users can easily go out and buy the correct tokens to trade on a hyperdrive pool.

Add Pool Information section to details page

---

apps/hyperdrive-trading/src/ui/base/components/Badge.tsx
apps/hyperdrive-trading/src/ui/base/components/GradientBadge.tsx
apps/hyperdrive-trading/src/ui/landing/Landing.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolStat.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx

Implements the redesigned pool row and hero section:

Add variable APY to pool row

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx

This PR fixes an overflow bug that we have on Morpho pools when a user LP's. It used to run over into the LP apy primary stat but now properly flexes.
https://github.com/user-attachments/assets/6bbf5da0-f6a4-429b-90ea-da57bea58a46
Closes #1569

fixes flex issue on lp

---

apps/hyperdrive-trading/src/ui/base/components/AccordionSection/AccordionSection.tsx
apps/hyperdrive-trading/src/ui/base/components/PrimaryStat.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortPreview/OpenShortPreview.tsx
apps/hyperdrive-trading/src/ui/markets/PointsMarkets/PointsMarkets.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
apps/hyperdrive-trading/src/version.output.ts

Closes #1674 
Matching the latest design for the Open Short form.
Additionally:
- fixed the right alignment of the second Primary stats on each open position form
- Added loading state skeleton to PoolRow to replace "-" character on Variable APY

Update OpenShortForm to show variable apy and multiplier together 

---

.vscode/settings.json
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/usePresentValue.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useUnpausedPools.ts
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts

Sorting requires TVL, which was throwing an error in getPresentValue and causing an infinite render loop. We need to fallback to TVL in terms of base in these cases.
We're waiting to see if defillama has delisted these tokens,, or if the fiat price endpoint will be fixed soon. If not, we'll need to find a new price sensor for nARS, Wrapped XDAI, and USDA.
USDA: https://coins.llama.fi/prices/current/ethereum:0x0000206329b97DB379d5E1Bf586BbDB969C63274
Wrapped XDai: https://coins.llama.fi/prices/current/gnosis:0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d
nARS: https://coins.llama.fi/prices/current/base:0x5e40f26E89213660514c51Fb61b2d357DBf63C85

Fix infinite loop due to missing fiat values

---

apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
apps/hyperdrive-trading/src/ui/app/Page.tsx
apps/hyperdrive-trading/src/ui/base/components/CustomBanner.tsx
apps/hyperdrive-trading/src/ui/globals.css
apps/hyperdrive-trading/src/ui/rewards/MilesBanner.tsx
apps/hyperdrive-trading/tailwind.config.js

Add banner for HyperVue Miles program

---

apps/hyperdrive-trading/src/ui/token/SlippageSettings.tsx

Unifying outline style of the Slippage setttings to match the sorting/filtering dropdowns on the list page. 
|Before|After|
|---|---|
|<img width="607" alt="image" src="https://github.com/user-attachments/assets/a5f9f366-e261-4e1a-afaa-275eceded77e" />|<img width="561" alt="image" src="https://github.com/user-attachments/assets/945fb75b-24b8-4ba9-984b-41efc09a1d90" />|

Polish Slippage Settings

---

apps/hyperdrive-trading/src/ui/token/hooks/useTokenAllowance.ts
apps/hyperdrive-trading/src/ui/token/hooks/useTokenBalance.ts

When not connected, `enabled` was resolving to `undefined` so the query was firing, but with no address argument.

Fix abi encoding errors in `useTokenAllowance` & `useTokenBalance`

---

apps/hyperdrive-trading/src/hyperdrive/getLpApy.ts
apps/hyperdrive-trading/src/hyperdrive/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/usePresentValue.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useUnpausedPools.ts
apps/hyperdrive-trading/src/ui/rewards/useRewards.ts
apps/hyperdrive-trading/src/ui/token/hooks/useTokenFiatPrice.ts

These functions were being called lots of extra times since the were never properly cached. This should cut down on requests to external apis.

Improve caching of rewards resolver functions and token fiat price

---

apps/hyperdrive-trading/src/ui/base/components/Well/Well.tsx
apps/hyperdrive-trading/src/ui/markets/PointsMarkets/PointsMarkets.tsx
apps/hyperdrive-trading/src/ui/markets/PointsMarkets/usePointsMultipliers.ts

The rewards multiplier is now wired up in both the banner and the Rewards Multiplier row.

Wire up Rewards Multiplier on Points Markets page

---

apps/hyperdrive-trading/src/ui/token/hooks/useTokenFiatPrice.ts

We were getting a flood of react query warnings when fetching due to a missing `enabled: true`.

Fix react-query warning about missing queryFn

---

apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/PointsMarkets/usePointsMultipliers.ts
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyStat.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip/RewardsTooltip.tsx
apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip/RewardsTooltipContent.tsx
apps/hyperdrive-trading/src/ui/rewards/hooks/getRewardResolverQuery.ts
apps/hyperdrive-trading/src/ui/rewards/hooks/useAddLiquidityRewards.ts
apps/hyperdrive-trading/src/ui/rewards/hooks/useOpenShortRewards.ts
apps/hyperdrive-trading/src/ui/rewards/queryKeys.ts
packages/hyperdrive-appconfig/src/index.ts
packages/hyperdrive-appconfig/src/rewards/selectors.ts
packages/hyperdrive-appconfig/src/yieldSources/selectors.ts

Rewards in the UI are now being read from the `appconfig.rewards` object for open short and add liquidity.
Once this lands, I'll:
- clean up the remaining deprecated callers (mostly `useYieldSourceRate`)
- remove any unused appconfig selectors and hooks
- remove any deprecated appconfig fields on `HyperdriveConfig` and `YieldSourceConfig` to complete the migration to the new rewards system

Wire up the RewardsTooltip to new rewards from appconfig

---

packages/hyperdrive-appconfig/src/appconfig/getAppConfig.ts
packages/hyperdrive-appconfig/src/rewards/actions/yieldSource.ts
packages/hyperdrive-appconfig/src/rewards/hyperdrive.ts

Unifying under a simple pattern for building up the rewards object in `getAppConfig`

Cleanup getAppConfig pattern for rewards

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx

This PR resolves the approval step in #1737 for implementing close long zap.
https://github.com/user-attachments/assets/89d24c05-cbdc-4855-924f-8b042a01f761

Close Long Zap Approval

---

apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useUnpausedPools.ts

Unhide susde/dai pool

---

apps/hyperdrive-trading/src/routeTree.gen.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongModalButton/CloseLongModalButton.tsx
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/LongsContainer.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/TotalOpenLongsValue/TotalOpenLongsValue.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/usePortfolioLongsData.ts
apps/hyperdrive-trading/src/ui/routes/portfolio.tsx

Moving the `account` into the url search params so that we can view any wallet's portfolio we want, not just the connected wallet.
This PR adds the new routing logic for the `account` param, and wires up the Longs tab. Other tabs to follow in the next PR.

Move account address into route for portfolio page

---

apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx

Checksumming the account address before calling the SDK with it is important, otherwise string comparisons between fields on events, eg: `spender` won't match the given account.

Checksum account from route before using it

---

apps/hyperdrive-trading/src/chains/isTestnetChain.ts
apps/hyperdrive-trading/src/ui/appconfig/useAppConfigForConnectedChain.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/usePreviewCloseLong.ts
apps/hyperdrive-trading/src/ui/hyperdrive/queryKeys.ts
apps/hyperdrive-trading/src/ui/main.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/OpenLongsTable/CurrentValueCell.tsx
apps/hyperdrive-trading/src/ui/token/hooks/useTokenFiatPrice.ts
packages/hyperdrive-appconfig/src/tokens/priceOracles/defillama.ts

This PR allows users to preview a close long position from any zap token.
Co-authored-by: Danny Delott <DannyDelott@users.noreply.github.com>

ZapBasedPreview

---

apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useTokenDepositOptions.ts
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
packages/hyperdrive-appconfig/src/tokens/selectors.ts

Unifying some duplicate logic found in all the open position forms.

Extract token options logic to own hook for open position forms

---

apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesTable/TotalLpValue.tsx

Fixes the total LP value in the portfolio for tokens with less than 18 decimals.
Fiat prices are always returned with the default decimals (`18`):
https://github.com/delvtech/hyperdrive-frontend/blob/4ea34c01ccab21571d8b47df2afd1daffe30f993/packages/hyperdrive-appconfig/src/tokens/priceOracles/defillama.ts#L31
But we were using the base token decimals when using it to determine price:
https://github.com/delvtech/hyperdrive-frontend/blob/4ea34c01ccab21571d8b47df2afd1daffe30f993/apps/hyperdrive-trading/src/ui/portfolio/lp/LpAndWithdrawalSharesTable/TotalLpValue.tsx#L57
This was inflating the value for USDC pools:

Fix total lp value in portfolio

---

.changeset/config.json
.github/workflows/release.yml

So we can manually trigger the release workflow (which will do nothing if everything is up to date).

Add dispatch trigger to release workflow

---

apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx

I still get insufficient allowance

fixed short padding

---

apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useReadHyperdrive.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useReadWriteHyperdrive.ts
apps/hyperdrive-trading/src/ui/hyperdrive/hooks/useUnpausedPools.ts
apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts
apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsTableDesktop.tsx
packages/hyperdrive-appconfig/src/rewards/knownTokenConfigs.ts

Followup to #1778. The pool list was breaking due to some missing optional chaining.

Fix bug causing pool lists to stop rendering

---

apps/hyperdrive-trading/src/ui/portfolio/rewards/RewardsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimableRewards.ts
apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimedRewards.ts
packages/hyperdrive-appconfig/src/rewards/resolvers/hypervueMiles.ts

Update miles tooltip copy

---

apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimableRewards.ts

Previously requesting a user's rewards would throw an error to signal "No rewards for this user". Now we get back a nice empty array and don't need to try/catch anymore.

Fix call to hyperdrive rewards server

---

apps/hyperdrive-trading/src/routeTree.gen.ts
apps/hyperdrive-trading/src/ui/base/components/MultiSelect.tsx
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimableRewards.ts

This removes the feature flag on the new `Rewards` tab in the Portfolio. Users can now see and claim their Hyperdrive Miles.

Remove feature flag on viewing and claiming Hyperdrive MIles

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx

The Pool Limited Exceeded is now shown in terms of the deposit token, not the max bonds.

Show max long in terms of active token

---

apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/rewards/merkl.ts
apps/hyperdrive-trading/src/routeTree.gen.ts
apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/markets/Leaderboard.tsx
apps/hyperdrive-trading/src/ui/rewards/hooks/useClaimableRewards.ts
apps/hyperdrive-trading/src/ui/rewards/routes.ts
apps/hyperdrive-trading/src/ui/routes/leaderboard.tsx
yarn.lock

Adds a leaderboard to showcase top Miles earners based on their total accumulated Miles.

Add Miles leaderboard

---

apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
packages/hyperdrive-appconfig/src/rewards/resolvers/morpho.ts

The `supplyApr` from morpho might come back as a javascript number with more than 18 numbers after the decimal place. This causes an error which break showing the list of pools, as the morpho rewards are required in the APY calculation displayed in the Pool rows.

Fixed Morpho reward resolver

---

apps/hyperdrive-trading/src/ui/base/components/LoadingState.tsx

Moving the spinner below the header to avoid jitter when loading states resolve and are replaced with a NonIdealState

Prevent jitter in LoadingState component

---

apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts

As @akhamisa noted, the default alphabetical sorting wasn’t working correctly because it sorted by the pool name, which always began with a duration prefix like “182d” or “91d.” By stripping this prefix before sorting, we ensure proper alphabetical ordering.

Fix bug in default sorting

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/hooks/useTotalOpenLongsValue.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/hooks/useTotalOpenLpPositions.ts
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/hooks/useTotalOpenShortsValue.ts

This PR removes the zap contract address from getHyperdrive on the totals hooks. This isn't required here even with Zaps fully implemented since they are only reading open positions which will be using base/shares tokens. There isn't a need to talk to the zap contract.

remove zapContractAddress from totals hooks

---

apps/hyperdrive-trading/src/rewards/getYieldSourceRate.ts
packages/hyperdrive-appconfig/src/rewards/resolvers/bigShortEnergy.ts

Use the correct reward resolver and fix the math so that we're correctly handling percents we get back from Merkl.

Fix resolver for Big Short Energy rewards

---

apps/hyperdrive-trading/src/rewards/getYieldSourceRate.ts
apps/hyperdrive-trading/src/ui/hyperdrive/lp/AddLiquidityForm/AddLiquidityForm.tsx
apps/hyperdrive-trading/src/ui/vaults/queryKeys.ts
apps/hyperdrive-trading/src/ui/vaults/useYieldSourceRate.ts

Quick hack to not include the BSE rewards in the LP apy. I'm implementing it once the silly way to see out how to implement it the serious way. Probably adding a field to `RewardConfig` that specifies if the LPs have exposure to the reward or something.. still not sure

Exclude BSE from LP Apy

---

apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts

Sorting by TVL by default, but with the pinned pools still at the top. Once you select a sort option, the pinned pools will end up in their correct TVL order.

Sort pools by tvl by default

---

.changeset/odd-ears-teach.md
apps/hyperdrive-trading/src/ui/analytics/ExternalLink.tsx
apps/hyperdrive-trading/src/ui/markets/PoolsList/PoolsList.tsx
apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip/RewardsTooltipContent.tsx
packages/hyperdrive-appconfig/src/rewards/resolvers/bigShortEnergy.ts
packages/hyperdrive-appconfig/src/rewards/types.ts

- Adds a link to more info about BSE in the pool row rewards tooltips.
- Adds an optional `moreInfoUrl` property to the `AnyRewards` type in appconfig
- Prevents click propagation on pool info tooltips
- Adds optional `icon` and `analyticsName` props to `ExternalLink` component

Add link to BSE info in pool row tooltip

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/CloseLongForm/CloseLongForm.tsx

If we're not zapping, don't show the allowance step for close Long

Don't require allowance to close long if not zapping

---

apps/hyperdrive-trading/src/ui/rewards/hooks/getRewardResolverQuery.ts

We can't rely on third-party reward resolvers to not throw errors on occassion, but that shouldn't be cause to not render the UI normally.

Catch error when requesting third party rewards

---

apps/hyperdrive-trading/src/ui/rewards/RewardsTooltip/RewardsTooltipContent.tsx
packages/hyperdrive-appconfig/src/rewards/resolvers/bigShortEnergy.ts
packages/hyperdrive-appconfig/src/rewards/resolvers/hypervueMiles.ts
packages/hyperdrive-appconfig/src/rewards/types.ts

Adds the `startTimestamp` and `endTimestamp` to the base reward type, and populates it for Big Short Energy from the Merkl API.
We show the end date of the reward program if we have it.

Show end date of Big Short Energy rewards in tooltip

---

apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx

Since the account already defaults to the connected one, we don't need to auto-add it to the URL. This helps ensure the account isn't stuck when switching wallets.

Remove auto url param on portfolio

---

apps/hyperdrive-trading/.env.sample
apps/hyperdrive-trading/package.json
apps/hyperdrive-trading/src/ui/base/debugging/wdyr.ts
apps/hyperdrive-trading/src/ui/base/memo.ts
apps/hyperdrive-trading/src/ui/main.tsx
apps/hyperdrive-trading/src/ui/markets/hooks/usePoolsList.ts
apps/hyperdrive-trading/vite.config.ts
turbo.json
yarn.lock

Adds a dev tool to get console logs about re-renders. To enable it you must set `VITE_ENABLE_WHY_DID_YOU_RENDER` to true in your .env.

Add why-did-you-render to profile React performance

---

apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongPreview/OpenLongStats.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/shorts/OpenShortForm/OpenShortForm.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolStat.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
apps/hyperdrive-trading/src/ui/markets/PositionPicker.tsx
apps/hyperdrive-trading/src/ui/onboarding/faqData2.tsx
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/OpenLongsTable/OpenLongsTableDesktop.tsx

As discussed, we're switching to displaying the implied APR for the variable rate in order to make the upside more clear and ease the transition into simpler "Fixed" and "Variable" terminology instead of "Long" and "Short".

Remove buttons from pool rows, switch to Short APR

---

apps/hyperdrive-trading/src/ui/portfolio/longs/OpenLongsTable/ManageLongsButton.tsx
apps/hyperdrive-trading/src/ui/portfolio/longs/OpenLongsTable/OpenLongsTableDesktop.tsx
apps/hyperdrive-trading/src/ui/portfolio/shorts/OpenShortsTable/ManageShortButton.tsx
apps/hyperdrive-trading/src/ui/portfolio/shorts/OpenShortsTable/OpenShortsTableDesktop.tsx

Reported by a user who noticed that if two positions are in the same checkpoint, the close modals weren't unique.

Fix close position button

---

apps/hyperdrive-trading/src/ui/app/Navbar/DevtoolsMenu.tsx
apps/hyperdrive-trading/src/ui/hyperdrive/longs/OpenLongForm/OpenLongForm.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/FixedAprCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/LpApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolRow.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/PoolStat.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyCta.tsx
apps/hyperdrive-trading/src/ui/markets/PoolRow/VariableApyStat.tsx
apps/hyperdrive-trading/src/ui/markets/PositionPicker.tsx
apps/hyperdrive-trading/src/ui/onboarding/faqData2.tsx
apps/hyperdrive-trading/src/ui/portfolio/Portfolio.tsx
packages/hyperdrive-js/package.json
packages/hyperdrive-js/src/hyperdrive/ReadHyperdrive.ts

In an effort to get the production branch back on track with staging, I'm putting the changes from #1831 behind a feature flag.

Put latest staging changes being feature flag

---

apps/hyperdrive-trading/src/network/wagmiClient.ts
apps/hyperdrive-trading/src/ui/app/Navbar/Navbar.tsx
apps/hyperdrive-trading/src/ui/chains/RpcForm.tsx
apps/hyperdrive-trading/src/ui/main.tsx

Adds an RPC Picker so you can set a different RPC Url for any of the connected chains:

Add RPC Picker

---

apps/hyperdrive-trading/src/base/latestBlocks.ts
apps/hyperdrive-trading/src/ui/portfolio/longs/usePortfolioLongsData.ts
apps/hyperdrive-trading/src/ui/portfolio/shorts/usePortfolioShortsData.ts

Partial patch to the portfolio queries which limits the "toBlock" of event queries for the longs and shorts. Some of the queries are still failing and will need to be broken up into smaller queries, but this gets us half way there so at least some positions will show up.

Add latest position blocks to portfolio queries
